/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Mudbase.SDK.Model;
using System.Runtime.CompilerServices;
using System.Net.Http.Headers;

[assembly: InternalsVisibleTo("Mudbase.SDK.Test")]

namespace Mudbase.SDK.Client
{
    /// <summary>
    /// Utility functions providing some benefit to API client consumers.
    /// </summary>
    public static partial class ClientUtils
    {

        /// <summary>
        /// A delegate for events.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        /// <returns></returns>
        public delegate void EventHandler<T>(object sender, T e) where T : EventArgs;

        /// <summary>
        /// An enum of headers
        /// </summary>
        public enum ApiKeyHeader
        {
            /// <summary>
            /// The X-API-Key header
            /// </summary>
            X_API_Key,
            /// <summary>
            /// The X-Internal-Api-Key header
            /// </summary>
            X_Internal_Api_Key
        }

        /// <summary>
        /// Converte an ApiKeyHeader to a string
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="System.ComponentModel.InvalidEnumArgumentException"></exception>
        public static string ApiKeyHeaderToString(ApiKeyHeader value)
        {
            return value switch
            {
                ApiKeyHeader.X_API_Key => "X-API-Key",
                ApiKeyHeader.X_Internal_Api_Key => "X-Internal-Api-Key",
                _ => throw new System.ComponentModel.InvalidEnumArgumentException(nameof(value), (int)value, typeof(ApiKeyHeader)),
            };
        }

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="json"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(string json, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(json, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="reader"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(ref Utf8JsonReader reader, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(ref reader, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// If parameter is DateTime, output in a formatted string (default ISO 8601), customizable with Configuration.DateTime.
        /// If parameter is a list, join the list with ",".
        /// Otherwise just return the string.
        /// </summary>
        /// <param name="obj">The parameter (header, path, query, form).</param>
        /// <param name="format">The DateTime serialization format.</param>
        /// <returns>Formatted string.</returns>
        public static string? ParameterToString(object? obj, string? format = ISO8601_DATETIME_FORMAT)
        {
            if (obj is DateTime dateTime)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTime.ToString(format);
            if (obj is DateTimeOffset dateTimeOffset)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTimeOffset.ToString(format);
            if (obj is DateOnly dateOnly)
                return dateOnly.ToString(format);
            if (obj is bool boolean)
                return boolean
                    ? "true"
                    : "false";
            if (obj is AddParticipantRequest.RoleEnum addParticipantRequestRoleEnum)
                return AddParticipantRequest.RoleEnumToJsonValue(addParticipantRequestRoleEnum);
            if (obj is AdminBillingCheckoutLinkRequest.PlanEnum adminBillingCheckoutLinkRequestPlanEnum)
                return AdminBillingCheckoutLinkRequest.PlanEnumToJsonValue(adminBillingCheckoutLinkRequestPlanEnum);
            if (obj is AdminBillingCheckoutLinkRequest.BillingCycleEnum adminBillingCheckoutLinkRequestBillingCycleEnum)
                return AdminBillingCheckoutLinkRequest.BillingCycleEnumToJsonValue(adminBillingCheckoutLinkRequestBillingCycleEnum);
            if (obj is AdminMemberRolePatchRequest.RoleEnum adminMemberRolePatchRequestRoleEnum)
                return AdminMemberRolePatchRequest.RoleEnumToJsonValue(adminMemberRolePatchRequestRoleEnum);
            if (obj is AdminOrgBillingContractPatchRequest.ContractBillingIntervalEnum adminOrgBillingContractPatchRequestContractBillingIntervalEnum)
                return AdminOrgBillingContractPatchRequest.ContractBillingIntervalEnumToJsonValue(adminOrgBillingContractPatchRequestContractBillingIntervalEnum);
            if (obj is AdminOrgLimitsPatchRequestBugAnalysis.QueueTypeEnum adminOrgLimitsPatchRequestBugAnalysisQueueTypeEnum)
                return AdminOrgLimitsPatchRequestBugAnalysis.QueueTypeEnumToJsonValue(adminOrgLimitsPatchRequestBugAnalysisQueueTypeEnum);
            if (obj is AdminOrgPlanPatchRequest.PlanEnum adminOrgPlanPatchRequestPlanEnum)
                return AdminOrgPlanPatchRequest.PlanEnumToJsonValue(adminOrgPlanPatchRequestPlanEnum);
            if (obj is AdminOrgPlanPatchRequest.TxPlanEnum adminOrgPlanPatchRequestTxPlanEnum)
                return AdminOrgPlanPatchRequest.TxPlanEnumToJsonValue(adminOrgPlanPatchRequestTxPlanEnum);
            if (obj is ApiGdprErasePostRequest.ConfirmEnum apiGdprErasePostRequestConfirmEnum)
                return ApiGdprErasePostRequest.ConfirmEnumToJsonValue(apiGdprErasePostRequestConfirmEnum);
            if (obj is ApiKeyPermission.ResourceEnum apiKeyPermissionResourceEnum)
                return ApiKeyPermission.ResourceEnumToJsonValue(apiKeyPermissionResourceEnum);
            if (obj is ApiKeyPermission.ActionsEnum apiKeyPermissionActionsEnum)
                return ApiKeyPermission.ActionsEnumToJsonValue(apiKeyPermissionActionsEnum);
            if (obj is ApiKycWorkflowsGet200ResponseWorkflowsInner.TypeEnum apiKycWorkflowsGet200ResponseWorkflowsInnerTypeEnum)
                return ApiKycWorkflowsGet200ResponseWorkflowsInner.TypeEnumToJsonValue(apiKycWorkflowsGet200ResponseWorkflowsInnerTypeEnum);
            if (obj is ApplyRoleFeaturePresetRequest.PresetEnum applyRoleFeaturePresetRequestPresetEnum)
                return ApplyRoleFeaturePresetRequest.PresetEnumToJsonValue(applyRoleFeaturePresetRequestPresetEnum);
            if (obj is BroadcastNonCustodialTransactionRequest.ChainEnum broadcastNonCustodialTransactionRequestChainEnum)
                return BroadcastNonCustodialTransactionRequest.ChainEnumToJsonValue(broadcastNonCustodialTransactionRequestChainEnum);
            if (obj is CalculateWalletFee200ResponseData.CongestionEnum calculateWalletFee200ResponseDataCongestionEnum)
                return CalculateWalletFee200ResponseData.CongestionEnumToJsonValue(calculateWalletFee200ResponseDataCongestionEnum);
            if (obj is CollectionAction collectionAction)
                return CollectionActionValueConverter.ToJsonValue(collectionAction);
            if (obj is ConfigureWebhook200ResponseDataTransformationsInner.TypeEnum configureWebhook200ResponseDataTransformationsInnerTypeEnum)
                return ConfigureWebhook200ResponseDataTransformationsInner.TypeEnumToJsonValue(configureWebhook200ResponseDataTransformationsInnerTypeEnum);
            if (obj is ConfirmUploadResponse.StatusEnum confirmUploadResponseStatusEnum)
                return ConfirmUploadResponse.StatusEnumToJsonValue(confirmUploadResponseStatusEnum);
            if (obj is CreateBackup201ResponseBackup.StatusEnum createBackup201ResponseBackupStatusEnum)
                return CreateBackup201ResponseBackup.StatusEnumToJsonValue(createBackup201ResponseBackupStatusEnum);
            if (obj is CreateChatRequest.TypeEnum createChatRequestTypeEnum)
                return CreateChatRequest.TypeEnumToJsonValue(createChatRequestTypeEnum);
            if (obj is CreateCheckoutSessionRequest.BillingCycleEnum createCheckoutSessionRequestBillingCycleEnum)
                return CreateCheckoutSessionRequest.BillingCycleEnumToJsonValue(createCheckoutSessionRequestBillingCycleEnum);
            if (obj is CreateOrUpdateFeeSettingsRequest.CurrencyEnum createOrUpdateFeeSettingsRequestCurrencyEnum)
                return CreateOrUpdateFeeSettingsRequest.CurrencyEnumToJsonValue(createOrUpdateFeeSettingsRequestCurrencyEnum);
            if (obj is CreatePlanRequest.IntervalEnum createPlanRequestIntervalEnum)
                return CreatePlanRequest.IntervalEnumToJsonValue(createPlanRequestIntervalEnum);
            if (obj is CreateRoleRequestPermissionsInner.ResourceEnum createRoleRequestPermissionsInnerResourceEnum)
                return CreateRoleRequestPermissionsInner.ResourceEnumToJsonValue(createRoleRequestPermissionsInnerResourceEnum);
            if (obj is CreateRoleRequestPermissionsInner.ActionsEnum createRoleRequestPermissionsInnerActionsEnum)
                return CreateRoleRequestPermissionsInner.ActionsEnumToJsonValue(createRoleRequestPermissionsInnerActionsEnum);
            if (obj is CreateWalletRequest.CurrencyEnum createWalletRequestCurrencyEnum)
                return CreateWalletRequest.CurrencyEnumToJsonValue(createWalletRequestCurrencyEnum);
            if (obj is CreateWalletWebhookRequest.EventsEnum createWalletWebhookRequestEventsEnum)
                return CreateWalletWebhookRequest.EventsEnumToJsonValue(createWalletWebhookRequestEventsEnum);
            if (obj is CreateWalletWebhookRequestFilters.ChainsEnum createWalletWebhookRequestFiltersChainsEnum)
                return CreateWalletWebhookRequestFilters.ChainsEnumToJsonValue(createWalletWebhookRequestFiltersChainsEnum);
            if (obj is DashboardOverviewDataLatency.ScopeEnum dashboardOverviewDataLatencyScopeEnum)
                return DashboardOverviewDataLatency.ScopeEnumToJsonValue(dashboardOverviewDataLatencyScopeEnum);
            if (obj is DashboardOverviewDataLatencyInstanceRollup.ScopeEnum dashboardOverviewDataLatencyInstanceRollupScopeEnum)
                return DashboardOverviewDataLatencyInstanceRollup.ScopeEnumToJsonValue(dashboardOverviewDataLatencyInstanceRollupScopeEnum);
            if (obj is DashboardOverviewDataRequests.DirectionEnum dashboardOverviewDataRequestsDirectionEnum)
                return DashboardOverviewDataRequests.DirectionEnumToJsonValue(dashboardOverviewDataRequestsDirectionEnum);
            if (obj is DashboardOverviewDataUptime.ScopeEnum dashboardOverviewDataUptimeScopeEnum)
                return DashboardOverviewDataUptime.ScopeEnumToJsonValue(dashboardOverviewDataUptimeScopeEnum);
            if (obj is EmailTemplateCatalogItem.EffectiveSourceEnum emailTemplateCatalogItemEffectiveSourceEnum)
                return EmailTemplateCatalogItem.EffectiveSourceEnumToJsonValue(emailTemplateCatalogItemEffectiveSourceEnum);
            if (obj is EmailTemplateResolved.EffectiveSourceEnum emailTemplateResolvedEffectiveSourceEnum)
                return EmailTemplateResolved.EffectiveSourceEnumToJsonValue(emailTemplateResolvedEffectiveSourceEnum);
            if (obj is EraseUserDataRequest.ConfirmEnum eraseUserDataRequestConfirmEnum)
                return EraseUserDataRequest.ConfirmEnumToJsonValue(eraseUserDataRequestConfirmEnum);
            if (obj is EstimateNetworkFeeRequest.CurrencyEnum estimateNetworkFeeRequestCurrencyEnum)
                return EstimateNetworkFeeRequest.CurrencyEnumToJsonValue(estimateNetworkFeeRequestCurrencyEnum);
            if (obj is EstimateNetworkFeeRequest.NetworkEnum estimateNetworkFeeRequestNetworkEnum)
                return EstimateNetworkFeeRequest.NetworkEnumToJsonValue(estimateNetworkFeeRequestNetworkEnum);
            if (obj is EstimateNonCustodialGasRequest.ChainEnum estimateNonCustodialGasRequestChainEnum)
                return EstimateNonCustodialGasRequest.ChainEnumToJsonValue(estimateNonCustodialGasRequestChainEnum);
            if (obj is ExecuteIntegrationRequest.MethodEnum executeIntegrationRequestMethodEnum)
                return ExecuteIntegrationRequest.MethodEnumToJsonValue(executeIntegrationRequestMethodEnum);
            if (obj is Field.TypeEnum fieldTypeEnum)
                return Field.TypeEnumToJsonValue(fieldTypeEnum);
            if (obj is FunctionExecution.InvokedByEnum functionExecutionInvokedByEnum)
                return FunctionExecution.InvokedByEnumToJsonValue(functionExecutionInvokedByEnum);
            if (obj is FunctionExecutionResponseData.StatusEnum functionExecutionResponseDataStatusEnum)
                return FunctionExecutionResponseData.StatusEnumToJsonValue(functionExecutionResponseDataStatusEnum);
            if (obj is FunctionExecutionStatusResponseData.StatusEnum functionExecutionStatusResponseDataStatusEnum)
                return FunctionExecutionStatusResponseData.StatusEnumToJsonValue(functionExecutionStatusResponseDataStatusEnum);
            if (obj is FunctionTrigger.TypeEnum functionTriggerTypeEnum)
                return FunctionTrigger.TypeEnumToJsonValue(functionTriggerTypeEnum);
            if (obj is FunctionTrigger.MethodEnum functionTriggerMethodEnum)
                return FunctionTrigger.MethodEnumToJsonValue(functionTriggerMethodEnum);
            if (obj is GeneratePrivateKeyRequest.CurrencyEnum generatePrivateKeyRequestCurrencyEnum)
                return GeneratePrivateKeyRequest.CurrencyEnumToJsonValue(generatePrivateKeyRequestCurrencyEnum);
            if (obj is GetCancelParamsRequest.ChainEnum getCancelParamsRequestChainEnum)
                return GetCancelParamsRequest.ChainEnumToJsonValue(getCancelParamsRequestChainEnum);
            if (obj is GetNetworkStatus200ResponseDataValue.CongestionEnum getNetworkStatus200ResponseDataValueCongestionEnum)
                return GetNetworkStatus200ResponseDataValue.CongestionEnumToJsonValue(getNetworkStatus200ResponseDataValueCongestionEnum);
            if (obj is GetOrganizationUsers200ResponseUsersInner.AccountStatusEnum getOrganizationUsers200ResponseUsersInnerAccountStatusEnum)
                return GetOrganizationUsers200ResponseUsersInner.AccountStatusEnumToJsonValue(getOrganizationUsers200ResponseUsersInnerAccountStatusEnum);
            if (obj is GetProjectCaptchaConfig200ResponseCaptcha.VarVersionEnum getProjectCaptchaConfig200ResponseCaptchaVarVersionEnum)
                return GetProjectCaptchaConfig200ResponseCaptcha.VarVersionEnumToJsonValue(getProjectCaptchaConfig200ResponseCaptchaVarVersionEnum);
            if (obj is GetSpeedUpParamsRequest.ChainEnum getSpeedUpParamsRequestChainEnum)
                return GetSpeedUpParamsRequest.ChainEnumToJsonValue(getSpeedUpParamsRequestChainEnum);
            if (obj is GetTransaction200ResponseData.TypeEnum getTransaction200ResponseDataTypeEnum)
                return GetTransaction200ResponseData.TypeEnumToJsonValue(getTransaction200ResponseDataTypeEnum);
            if (obj is GetTransaction200ResponseData.MainTxStatusEnum getTransaction200ResponseDataMainTxStatusEnum)
                return GetTransaction200ResponseData.MainTxStatusEnumToJsonValue(getTransaction200ResponseDataMainTxStatusEnum);
            if (obj is GetTransaction200ResponseData.RefundStatusEnum getTransaction200ResponseDataRefundStatusEnum)
                return GetTransaction200ResponseData.RefundStatusEnumToJsonValue(getTransaction200ResponseDataRefundStatusEnum);
            if (obj is GetTransaction200ResponseData.StatusEnum getTransaction200ResponseDataStatusEnum)
                return GetTransaction200ResponseData.StatusEnumToJsonValue(getTransaction200ResponseDataStatusEnum);
            if (obj is GetWebhookConfig200ResponseDataTransformationsInner.TypeEnum getWebhookConfig200ResponseDataTransformationsInnerTypeEnum)
                return GetWebhookConfig200ResponseDataTransformationsInner.TypeEnumToJsonValue(getWebhookConfig200ResponseDataTransformationsInnerTypeEnum);
            if (obj is HealthResponse.StatusEnum healthResponseStatusEnum)
                return HealthResponse.StatusEnumToJsonValue(healthResponseStatusEnum);
            if (obj is InitializeOrgPlanCheckoutRequest.PlanNameEnum initializeOrgPlanCheckoutRequestPlanNameEnum)
                return InitializeOrgPlanCheckoutRequest.PlanNameEnumToJsonValue(initializeOrgPlanCheckoutRequestPlanNameEnum);
            if (obj is InitializeOrgPlanCheckoutRequest.BillingCycleEnum initializeOrgPlanCheckoutRequestBillingCycleEnum)
                return InitializeOrgPlanCheckoutRequest.BillingCycleEnumToJsonValue(initializeOrgPlanCheckoutRequestBillingCycleEnum);
            if (obj is InviteMemberRequest.RoleEnum inviteMemberRequestRoleEnum)
                return InviteMemberRequest.RoleEnumToJsonValue(inviteMemberRequestRoleEnum);
            if (obj is LogSecurityEventRequest.EventTypeEnum logSecurityEventRequestEventTypeEnum)
                return LogSecurityEventRequest.EventTypeEnumToJsonValue(logSecurityEventRequestEventTypeEnum);
            if (obj is LogSecurityEventRequest.SeverityEnum logSecurityEventRequestSeverityEnum)
                return LogSecurityEventRequest.SeverityEnumToJsonValue(logSecurityEventRequestSeverityEnum);
            if (obj is Message.TypeEnum messageTypeEnum)
                return Message.TypeEnumToJsonValue(messageTypeEnum);
            if (obj is Message.StatusEnum messageStatusEnum)
                return Message.StatusEnumToJsonValue(messageStatusEnum);
            if (obj is NonCustodialAddress.ChainEnum nonCustodialAddressChainEnum)
                return NonCustodialAddress.ChainEnumToJsonValue(nonCustodialAddressChainEnum);
            if (obj is OTPSendRequest.MethodEnum oTPSendRequestMethodEnum)
                return OTPSendRequest.MethodEnumToJsonValue(oTPSendRequestMethodEnum);
            if (obj is OrgDomainEntryOrgConsole.SourceEnum orgDomainEntryOrgConsoleSourceEnum)
                return OrgDomainEntryOrgConsole.SourceEnumToJsonValue(orgDomainEntryOrgConsoleSourceEnum);
            if (obj is OrgDomainEntryWithDns.SourceEnum orgDomainEntryWithDnsSourceEnum)
                return OrgDomainEntryWithDns.SourceEnumToJsonValue(orgDomainEntryWithDnsSourceEnum);
            if (obj is Organization.DeploymentTypeEnum organizationDeploymentTypeEnum)
                return Organization.DeploymentTypeEnumToJsonValue(organizationDeploymentTypeEnum);
            if (obj is PatchOrgDomainRequest.StatusEnum patchOrgDomainRequestStatusEnum)
                return PatchOrgDomainRequest.StatusEnumToJsonValue(patchOrgDomainRequestStatusEnum);
            if (obj is Permission.ActionsEnum permissionActionsEnum)
                return Permission.ActionsEnumToJsonValue(permissionActionsEnum);
            if (obj is PresignedPostResponse.MethodEnum presignedPostResponseMethodEnum)
                return PresignedPostResponse.MethodEnumToJsonValue(presignedPostResponseMethodEnum);
            if (obj is ProjectEmailSendRequest.BrandingScopeEnum projectEmailSendRequestBrandingScopeEnum)
                return ProjectEmailSendRequest.BrandingScopeEnumToJsonValue(projectEmailSendRequestBrandingScopeEnum);
            if (obj is ProjectSettings.DefaultUserAccountStatusEnum projectSettingsDefaultUserAccountStatusEnum)
                return ProjectSettings.DefaultUserAccountStatusEnumToJsonValue(projectSettingsDefaultUserAccountStatusEnum);
            if (obj is ProjectSmsByoPatchRequest.ProviderEnum projectSmsByoPatchRequestProviderEnum)
                return ProjectSmsByoPatchRequest.ProviderEnumToJsonValue(projectSmsByoPatchRequestProviderEnum);
            if (obj is ProjectSmsByoPublic.ProviderEnum projectSmsByoPublicProviderEnum)
                return ProjectSmsByoPublic.ProviderEnumToJsonValue(projectSmsByoPublicProviderEnum);
            if (obj is RegisterNonCustodialAddressRequest.ChainEnum registerNonCustodialAddressRequestChainEnum)
                return RegisterNonCustodialAddressRequest.ChainEnumToJsonValue(registerNonCustodialAddressRequestChainEnum);
            if (obj is RequestRoleElevation200Response.WorkflowEnum requestRoleElevation200ResponseWorkflowEnum)
                return RequestRoleElevation200Response.WorkflowEnumToJsonValue(requestRoleElevation200ResponseWorkflowEnum);
            if (obj is RequestRoleElevation200Response.StatusEnum requestRoleElevation200ResponseStatusEnum)
                return RequestRoleElevation200Response.StatusEnumToJsonValue(requestRoleElevation200ResponseStatusEnum);
            if (obj is RestoreBackup200ResponseRestore.StatusEnum restoreBackup200ResponseRestoreStatusEnum)
                return RestoreBackup200ResponseRestore.StatusEnumToJsonValue(restoreBackup200ResponseRestoreStatusEnum);
            if (obj is RestoreBackupRequest.ConfirmationEnum restoreBackupRequestConfirmationEnum)
                return RestoreBackupRequest.ConfirmationEnumToJsonValue(restoreBackupRequestConfirmationEnum);
            if (obj is RestoreBackupRequest.RestoreModeEnum restoreBackupRequestRestoreModeEnum)
                return RestoreBackupRequest.RestoreModeEnumToJsonValue(restoreBackupRequestRestoreModeEnum);
            if (obj is SendMessageRequest.TypeEnum sendMessageRequestTypeEnum)
                return SendMessageRequest.TypeEnumToJsonValue(sendMessageRequestTypeEnum);
            if (obj is SimulateAppPermissions200Response.ReasonEnum simulateAppPermissions200ResponseReasonEnum)
                return SimulateAppPermissions200Response.ReasonEnumToJsonValue(simulateAppPermissions200ResponseReasonEnum);
            if (obj is TriggerWebhookRequest.MethodEnum triggerWebhookRequestMethodEnum)
                return TriggerWebhookRequest.MethodEnumToJsonValue(triggerWebhookRequestMethodEnum);
            if (obj is UpdateCollectionPermissionsRequest.ActionsEnum updateCollectionPermissionsRequestActionsEnum)
                return UpdateCollectionPermissionsRequest.ActionsEnumToJsonValue(updateCollectionPermissionsRequestActionsEnum);
            if (obj is UpdateCollectionPermissionsRequest.DataScopeEnum updateCollectionPermissionsRequestDataScopeEnum)
                return UpdateCollectionPermissionsRequest.DataScopeEnumToJsonValue(updateCollectionPermissionsRequestDataScopeEnum);
            if (obj is UpdateMemberRoleRequest.RoleEnum updateMemberRoleRequestRoleEnum)
                return UpdateMemberRoleRequest.RoleEnumToJsonValue(updateMemberRoleRequestRoleEnum);
            if (obj is UpdateOrganizationPlanRequest.PlanEnum updateOrganizationPlanRequestPlanEnum)
                return UpdateOrganizationPlanRequest.PlanEnumToJsonValue(updateOrganizationPlanRequestPlanEnum);
            if (obj is UpdateUserAccountStatusRequest.AccountStatusEnum updateUserAccountStatusRequestAccountStatusEnum)
                return UpdateUserAccountStatusRequest.AccountStatusEnumToJsonValue(updateUserAccountStatusRequestAccountStatusEnum);
            if (obj is User.RoleEnum userRoleEnum)
                return User.RoleEnumToJsonValue(userRoleEnum);
            if (obj is ValidateAddressRequest.CurrencyEnum validateAddressRequestCurrencyEnum)
                return ValidateAddressRequest.CurrencyEnumToJsonValue(validateAddressRequestCurrencyEnum);
            if (obj is VerifyPayment200ResponseDataSubscription.StatusEnum verifyPayment200ResponseDataSubscriptionStatusEnum)
                return VerifyPayment200ResponseDataSubscription.StatusEnumToJsonValue(verifyPayment200ResponseDataSubscriptionStatusEnum);
            if (obj is WalletTransaction.StatusEnum walletTransactionStatusEnum)
                return WalletTransaction.StatusEnumToJsonValue(walletTransactionStatusEnum);
            if (obj is WalletTransaction.MainTxStatusEnum walletTransactionMainTxStatusEnum)
                return WalletTransaction.MainTxStatusEnumToJsonValue(walletTransactionMainTxStatusEnum);
            if (obj is WalletWebhook.EventsEnum walletWebhookEventsEnum)
                return WalletWebhook.EventsEnumToJsonValue(walletWebhookEventsEnum);
            if (obj is WalletWebhookFilters.ChainsEnum walletWebhookFiltersChainsEnum)
                return WalletWebhookFilters.ChainsEnumToJsonValue(walletWebhookFiltersChainsEnum);
            if (obj is WebhookLog.MethodEnum webhookLogMethodEnum)
                return WebhookLog.MethodEnumToJsonValue(webhookLogMethodEnum);
            if (obj is WebhookLog.StatusEnum webhookLogStatusEnum)
                return WebhookLog.StatusEnumToJsonValue(webhookLogStatusEnum);
            if (obj is Withdraw200ResponseData.StatusEnum withdraw200ResponseDataStatusEnum)
                return Withdraw200ResponseData.StatusEnumToJsonValue(withdraw200ResponseDataStatusEnum);
            if (obj is ICollection collection)
            {
                List<string?> entries = new();
                foreach (var entry in collection)
                    entries.Add(ParameterToString(entry));
                return string.Join(",", entries);
            }

            return Convert.ToString(obj, System.Globalization.CultureInfo.InvariantCulture);
        }

        /// <summary>
        /// URL encode a string
        /// Credit/Ref: https://github.com/restsharp/RestSharp/blob/master/RestSharp/Extensions/StringExtensions.cs#L50
        /// </summary>
        /// <param name="input">string to be URL encoded</param>
        /// <returns>Byte array</returns>
        public static string UrlEncode(string input)
        {
            const int maxLength = 32766;

            if (input == null)
            {
                throw new ArgumentNullException("input");
            }

            if (input.Length <= maxLength)
            {
                return Uri.EscapeDataString(input);
            }

            StringBuilder sb = new StringBuilder(input.Length * 2);
            int index = 0;

            while (index < input.Length)
            {
                int length = Math.Min(input.Length - index, maxLength);
                string subString = input.Substring(index, length);

                sb.Append(Uri.EscapeDataString(subString));
                index += subString.Length;
            }

            return sb.ToString();
        }

        /// <summary>
        /// Encode string in base64 format.
        /// </summary>
        /// <param name="text">string to be encoded.</param>
        /// <returns>Encoded string.</returns>
        public static string Base64Encode(string text)
        {
            return Convert.ToBase64String(global::System.Text.Encoding.UTF8.GetBytes(text));
        }

        /// <summary>
        /// Convert stream to byte array
        /// </summary>
        /// <param name="inputStream">Input stream to be converted</param>
        /// <returns>Byte array</returns>
        public static byte[] ReadAsBytes(Stream inputStream)
        {
            using (var ms = new MemoryStream())
            {
                inputStream.CopyTo(ms);
                return ms.ToArray();
            }
        }

        /// <summary>
        /// Select the Content-Type header's value from the given content-type array:
        /// if JSON type exists in the given array, use it;
        /// otherwise use the first one defined in 'consumes'
        /// </summary>
        /// <param name="contentTypes">The Content-Type array to select from.</param>
        /// <returns>The Content-Type header to use.</returns>
        public static string? SelectHeaderContentType(string[] contentTypes)
        {
            if (contentTypes.Length == 0)
                return null;

            foreach (var contentType in contentTypes)
            {
                if (IsJsonMime(contentType))
                    return contentType;
            }

            return contentTypes[0]; // use the first content type specified in 'consumes'
        }

        /// <summary>
        /// Select the Accept header's value from the given accepts array:
        /// if JSON exists in the given array, use it;
        /// otherwise use all of them (joining into a string)
        /// </summary>
        /// <param name="accepts">The accepts array to select from.</param>
        /// <returns>The Accept header to use.</returns>
        public static string? SelectHeaderAccept(string[] accepts)
        {
            if (accepts.Length == 0)
                return null;

            if (accepts.Contains("application/json", StringComparer.OrdinalIgnoreCase))
                return "application/json";

            return string.Join(",", accepts);
        }

        

        /// <summary>
        /// Select the Accept header's value from the given accepts array:
        /// if JSON exists in the given array, use it;
        /// otherwise use all of them.
        /// </summary>
        /// <param name="accepts">The accepts array to select from.</param>
        /// <returns>The Accept header values to use.</returns>
        public static IEnumerable<MediaTypeWithQualityHeaderValue> SelectHeaderAcceptArray(string[] accepts)
        {
            if (accepts.Length == 0)
                    return [];

            if (accepts.Contains("application/json", StringComparer.OrdinalIgnoreCase))
                    return [MediaTypeWithQualityHeaderValue.Parse("application/json")];

            return accepts.Select(MediaTypeWithQualityHeaderValue.Parse);
        }

        /// <summary>
        /// Provides a case-insensitive check that a provided content type is a known JSON-like content type.
        /// </summary>
        [GeneratedRegex("(?i)^(application/json|[^;/ \t]+/[^;/ \t]+[+]json)[ \t]*(;.*)?$")]
        private static partial Regex JsonRegex();

        /// <summary>
        /// Check if the given MIME is a JSON MIME.
        /// JSON MIME examples:
        ///    application/json
        ///    application/json; charset=UTF8
        ///    APPLICATION/JSON
        ///    application/vnd.company+json
        /// </summary>
        /// <param name="mime">MIME</param>
        /// <returns>Returns True if MIME type is json.</returns>
        public static bool IsJsonMime(string mime)
        {
            if (string.IsNullOrWhiteSpace(mime)) return false;

            return JsonRegex().IsMatch(mime) || mime.Equals("application/json-patch+json");
        }

        /// <summary>
        /// Get the discriminator
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="discriminator"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public static string? GetDiscriminator(Utf8JsonReader utf8JsonReader, string discriminator)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    if (localVarJsonPropertyName != null && localVarJsonPropertyName.Equals(discriminator))
                        return utf8JsonReader.GetString();
                }
            }

            throw new JsonException("The specified discriminator was not found.");
        }

        /// <summary>
        /// The base path of the API
        /// </summary>
        public const string BASE_ADDRESS = "https://cloud.mudbase.dev";

        /// <summary>
        /// The scheme of the API
        /// </summary>
        public const string SCHEME = "https";

        /// <summary>
        /// The context path of the API
        /// </summary>
        public const string CONTEXT_PATH = "";

        /// <summary>
        /// The host of the API
        /// </summary>
        public const string HOST = "cloud.mudbase.dev";

        /// <summary>
        /// The format to use for DateTime serialization
        /// </summary>
        public const string ISO8601_DATETIME_FORMAT = "o";
    }
}
