/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave for fiat (platform subscriptions and payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.12
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mudbase.SDK.Model;
using Mudbase.SDK.Client;
using System.Reflection;

namespace Mudbase.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing FileMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileMetadata
        //private FileMetadata instance;

        public FileMetadataTests()
        {
            // TODO uncomment below to create an instance of FileMetadata
            //instance = new FileMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileMetadata
        /// </summary>
        [Fact]
        public void FileMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileMetadata
            //Assert.IsType<FileMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'OriginalName'
        /// </summary>
        [Fact]
        public void OriginalNameTest()
        {
            // TODO unit test for the property 'OriginalName'
        }

        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Fact]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'PublicUrl'
        /// </summary>
        [Fact]
        public void PublicUrlTest()
        {
            // TODO unit test for the property 'PublicUrl'
        }

        /// <summary>
        /// Test the property 'Bucket'
        /// </summary>
        [Fact]
        public void BucketTest()
        {
            // TODO unit test for the property 'Bucket'
        }

        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Fact]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }

        /// <summary>
        /// Test the property 'UploadedBy'
        /// </summary>
        [Fact]
        public void UploadedByTest()
        {
            // TODO unit test for the property 'UploadedBy'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
