/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.7
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mudbase.SDK.Model;
using Mudbase.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mudbase.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateWalletWebhook200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateWalletWebhook200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateWalletWebhook200Response
        //private UpdateWalletWebhook200Response instance;

        public UpdateWalletWebhook200ResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateWalletWebhook200Response
            //instance = new UpdateWalletWebhook200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateWalletWebhook200Response
        /// </summary>
        [Fact]
        public void UpdateWalletWebhook200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateWalletWebhook200Response
            //Assert.IsType<UpdateWalletWebhook200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
