/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.9
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mudbase.SDK.Model;
using Mudbase.SDK.Client;
using System.Reflection;

namespace Mudbase.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing WalletBroadcastTransaction200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletBroadcastTransaction200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletBroadcastTransaction200ResponseData
        //private WalletBroadcastTransaction200ResponseData instance;

        public WalletBroadcastTransaction200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of WalletBroadcastTransaction200ResponseData
            //instance = new WalletBroadcastTransaction200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletBroadcastTransaction200ResponseData
        /// </summary>
        [Fact]
        public void WalletBroadcastTransaction200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletBroadcastTransaction200ResponseData
            //Assert.IsType<WalletBroadcastTransaction200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'TxHash'
        /// </summary>
        [Fact]
        public void TxHashTest()
        {
            // TODO unit test for the property 'TxHash'
        }

        /// <summary>
        /// Test the property 'Chain'
        /// </summary>
        [Fact]
        public void ChainTest()
        {
            // TODO unit test for the property 'Chain'
        }

        /// <summary>
        /// Test the property 'FromAddress'
        /// </summary>
        [Fact]
        public void FromAddressTest()
        {
            // TODO unit test for the property 'FromAddress'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
    }
}
