// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// AddCustomRoleRequestDefaultPermissionsInner
    /// </summary>
    public partial class AddCustomRoleRequestDefaultPermissionsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddCustomRoleRequestDefaultPermissionsInner" /> class.
        /// </summary>
        /// <param name="resource">resource</param>
        /// <param name="actions">actions</param>
        [JsonConstructor]
        public AddCustomRoleRequestDefaultPermissionsInner(Option<string?> resource = default, Option<List<string>?> actions = default)
        {
            ResourceOption = resource;
            ActionsOption = actions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Resource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Resource
        /// </summary>
        [JsonPropertyName("resource")]
        public string? Resource { get { return this.ResourceOption; } set { this.ResourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Actions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ActionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Actions
        /// </summary>
        [JsonPropertyName("actions")]
        public List<string>? Actions { get { return this.ActionsOption; } set { this.ActionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddCustomRoleRequestDefaultPermissionsInner {\n");
            sb.Append("  Resource: ").Append(Resource).Append("\n");
            sb.Append("  Actions: ").Append(Actions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddCustomRoleRequestDefaultPermissionsInner" />
    /// </summary>
    public class AddCustomRoleRequestDefaultPermissionsInnerJsonConverter : JsonConverter<AddCustomRoleRequestDefaultPermissionsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddCustomRoleRequestDefaultPermissionsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddCustomRoleRequestDefaultPermissionsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> resource = default;
            Option<List<string>?> actions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "resource":
                            resource = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "actions":
                            actions = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (resource.IsSet && resource.Value == null)
                throw new ArgumentNullException(nameof(resource), "Property is not nullable for class AddCustomRoleRequestDefaultPermissionsInner.");

            if (actions.IsSet && actions.Value == null)
                throw new ArgumentNullException(nameof(actions), "Property is not nullable for class AddCustomRoleRequestDefaultPermissionsInner.");

            return new AddCustomRoleRequestDefaultPermissionsInner(resource, actions);
        }

        /// <summary>
        /// Serializes a <see cref="AddCustomRoleRequestDefaultPermissionsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addCustomRoleRequestDefaultPermissionsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddCustomRoleRequestDefaultPermissionsInner addCustomRoleRequestDefaultPermissionsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addCustomRoleRequestDefaultPermissionsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddCustomRoleRequestDefaultPermissionsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addCustomRoleRequestDefaultPermissionsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddCustomRoleRequestDefaultPermissionsInner addCustomRoleRequestDefaultPermissionsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addCustomRoleRequestDefaultPermissionsInner.ResourceOption.IsSet && addCustomRoleRequestDefaultPermissionsInner.Resource == null)
                throw new ArgumentNullException(nameof(addCustomRoleRequestDefaultPermissionsInner.Resource), "Property is required for class AddCustomRoleRequestDefaultPermissionsInner.");

            if (addCustomRoleRequestDefaultPermissionsInner.ActionsOption.IsSet && addCustomRoleRequestDefaultPermissionsInner.Actions == null)
                throw new ArgumentNullException(nameof(addCustomRoleRequestDefaultPermissionsInner.Actions), "Property is required for class AddCustomRoleRequestDefaultPermissionsInner.");

            if (addCustomRoleRequestDefaultPermissionsInner.ResourceOption.IsSet)
                writer.WriteString("resource", addCustomRoleRequestDefaultPermissionsInner.Resource);

            if (addCustomRoleRequestDefaultPermissionsInner.ActionsOption.IsSet)
            {
                writer.WritePropertyName("actions");
                JsonSerializer.Serialize(writer, addCustomRoleRequestDefaultPermissionsInner.Actions, jsonSerializerOptions);
            }
        }
    }
}
