// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// AdminProvisionEnterpriseBody
    /// </summary>
    public partial class AdminProvisionEnterpriseBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdminProvisionEnterpriseBody" /> class.
        /// </summary>
        /// <param name="provisionRequestId">provisionRequestId</param>
        /// <param name="apiBaseUrl">apiBaseUrl</param>
        /// <param name="dbRef">dbRef</param>
        /// <param name="serverId">serverId</param>
        /// <param name="region">region</param>
        /// <param name="varVersion">varVersion</param>
        /// <param name="forceOverride">forceOverride</param>
        [JsonConstructor]
        public AdminProvisionEnterpriseBody(string provisionRequestId, string apiBaseUrl, string dbRef, string serverId, Option<string?> region = default, Option<string?> varVersion = default, Option<bool?> forceOverride = default)
        {
            ProvisionRequestId = provisionRequestId;
            ApiBaseUrl = apiBaseUrl;
            DbRef = dbRef;
            ServerId = serverId;
            RegionOption = region;
            VarVersionOption = varVersion;
            ForceOverrideOption = forceOverride;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProvisionRequestId
        /// </summary>
        [JsonPropertyName("provisionRequestId")]
        public string ProvisionRequestId { get; set; }

        /// <summary>
        /// Gets or Sets ApiBaseUrl
        /// </summary>
        [JsonPropertyName("apiBaseUrl")]
        public string ApiBaseUrl { get; set; }

        /// <summary>
        /// Gets or Sets DbRef
        /// </summary>
        [JsonPropertyName("dbRef")]
        public string DbRef { get; set; }

        /// <summary>
        /// Gets or Sets ServerId
        /// </summary>
        [JsonPropertyName("serverId")]
        public string ServerId { get; set; }

        /// <summary>
        /// Used to track the state of Region
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RegionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        [JsonPropertyName("region")]
        public string? Region { get { return this.RegionOption; } set { this.RegionOption = new(value); } }

        /// <summary>
        /// Used to track the state of VarVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VarVersionOption { get; private set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [JsonPropertyName("version")]
        public string? VarVersion { get { return this.VarVersionOption; } set { this.VarVersionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ForceOverride
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ForceOverrideOption { get; private set; }

        /// <summary>
        /// Gets or Sets ForceOverride
        /// </summary>
        [JsonPropertyName("forceOverride")]
        public bool? ForceOverride { get { return this.ForceOverrideOption; } set { this.ForceOverrideOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdminProvisionEnterpriseBody {\n");
            sb.Append("  ProvisionRequestId: ").Append(ProvisionRequestId).Append("\n");
            sb.Append("  ApiBaseUrl: ").Append(ApiBaseUrl).Append("\n");
            sb.Append("  DbRef: ").Append(DbRef).Append("\n");
            sb.Append("  ServerId: ").Append(ServerId).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  ForceOverride: ").Append(ForceOverride).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AdminProvisionEnterpriseBody" />
    /// </summary>
    public class AdminProvisionEnterpriseBodyJsonConverter : JsonConverter<AdminProvisionEnterpriseBody>
    {
        /// <summary>
        /// Deserializes json to <see cref="AdminProvisionEnterpriseBody" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AdminProvisionEnterpriseBody Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> provisionRequestId = default;
            Option<string?> apiBaseUrl = default;
            Option<string?> dbRef = default;
            Option<string?> serverId = default;
            Option<string?> region = default;
            Option<string?> varVersion = default;
            Option<bool?> forceOverride = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "provisionRequestId":
                            provisionRequestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "apiBaseUrl":
                            apiBaseUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dbRef":
                            dbRef = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "serverId":
                            serverId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "region":
                            region = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "version":
                            varVersion = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "forceOverride":
                            forceOverride = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!provisionRequestId.IsSet)
                throw new ArgumentException("Property is required for class AdminProvisionEnterpriseBody.", nameof(provisionRequestId));

            if (!apiBaseUrl.IsSet)
                throw new ArgumentException("Property is required for class AdminProvisionEnterpriseBody.", nameof(apiBaseUrl));

            if (!dbRef.IsSet)
                throw new ArgumentException("Property is required for class AdminProvisionEnterpriseBody.", nameof(dbRef));

            if (!serverId.IsSet)
                throw new ArgumentException("Property is required for class AdminProvisionEnterpriseBody.", nameof(serverId));

            if (provisionRequestId.IsSet && provisionRequestId.Value == null)
                throw new ArgumentNullException(nameof(provisionRequestId), "Property is not nullable for class AdminProvisionEnterpriseBody.");

            if (apiBaseUrl.IsSet && apiBaseUrl.Value == null)
                throw new ArgumentNullException(nameof(apiBaseUrl), "Property is not nullable for class AdminProvisionEnterpriseBody.");

            if (dbRef.IsSet && dbRef.Value == null)
                throw new ArgumentNullException(nameof(dbRef), "Property is not nullable for class AdminProvisionEnterpriseBody.");

            if (serverId.IsSet && serverId.Value == null)
                throw new ArgumentNullException(nameof(serverId), "Property is not nullable for class AdminProvisionEnterpriseBody.");

            if (forceOverride.IsSet && forceOverride.Value == null)
                throw new ArgumentNullException(nameof(forceOverride), "Property is not nullable for class AdminProvisionEnterpriseBody.");

            return new AdminProvisionEnterpriseBody(provisionRequestId.Value!, apiBaseUrl.Value!, dbRef.Value!, serverId.Value!, region, varVersion, forceOverride);
        }

        /// <summary>
        /// Serializes a <see cref="AdminProvisionEnterpriseBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="adminProvisionEnterpriseBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AdminProvisionEnterpriseBody adminProvisionEnterpriseBody, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, adminProvisionEnterpriseBody, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AdminProvisionEnterpriseBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="adminProvisionEnterpriseBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AdminProvisionEnterpriseBody adminProvisionEnterpriseBody, JsonSerializerOptions jsonSerializerOptions)
        {
            if (adminProvisionEnterpriseBody.ProvisionRequestId == null)
                throw new ArgumentNullException(nameof(adminProvisionEnterpriseBody.ProvisionRequestId), "Property is required for class AdminProvisionEnterpriseBody.");

            if (adminProvisionEnterpriseBody.ApiBaseUrl == null)
                throw new ArgumentNullException(nameof(adminProvisionEnterpriseBody.ApiBaseUrl), "Property is required for class AdminProvisionEnterpriseBody.");

            if (adminProvisionEnterpriseBody.DbRef == null)
                throw new ArgumentNullException(nameof(adminProvisionEnterpriseBody.DbRef), "Property is required for class AdminProvisionEnterpriseBody.");

            if (adminProvisionEnterpriseBody.ServerId == null)
                throw new ArgumentNullException(nameof(adminProvisionEnterpriseBody.ServerId), "Property is required for class AdminProvisionEnterpriseBody.");

            writer.WriteString("provisionRequestId", adminProvisionEnterpriseBody.ProvisionRequestId);

            writer.WriteString("apiBaseUrl", adminProvisionEnterpriseBody.ApiBaseUrl);

            writer.WriteString("dbRef", adminProvisionEnterpriseBody.DbRef);

            writer.WriteString("serverId", adminProvisionEnterpriseBody.ServerId);

            if (adminProvisionEnterpriseBody.RegionOption.IsSet)
                if (adminProvisionEnterpriseBody.RegionOption.Value != null)
                    writer.WriteString("region", adminProvisionEnterpriseBody.Region);
                else
                    writer.WriteNull("region");

            if (adminProvisionEnterpriseBody.VarVersionOption.IsSet)
                if (adminProvisionEnterpriseBody.VarVersionOption.Value != null)
                    writer.WriteString("version", adminProvisionEnterpriseBody.VarVersion);
                else
                    writer.WriteNull("version");

            if (adminProvisionEnterpriseBody.ForceOverrideOption.IsSet)
                writer.WriteBoolean("forceOverride", adminProvisionEnterpriseBody.ForceOverrideOption.Value!.Value);
        }
    }
}
