/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.4
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mudbase.SDK.Client.FileParameter;
using OpenAPIDateConverter = Mudbase.SDK.Client.OpenAPIDateConverter;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// Partial org limit overrides for platform admins. At least one property required. Keys match &#x60;PLANS[*].limits&#x60; in the backend; integers are non-negative or null for unlimited. 
    /// </summary>
    [DataContract(Name = "AdminOrgLimitsPatchRequest")]
    public partial class AdminOrgLimitsPatchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdminOrgLimitsPatchRequest" /> class.
        /// </summary>
        /// <param name="projects">projects.</param>
        /// <param name="storage">storage.</param>
        /// <param name="bandwidth">bandwidth.</param>
        /// <param name="apiCalls">apiCalls.</param>
        /// <param name="buckets">buckets.</param>
        /// <param name="collections">collections.</param>
        /// <param name="realtimeConnections">realtimeConnections.</param>
        /// <param name="realtimeMessages">realtimeMessages.</param>
        /// <param name="chatMessagesPerMonth">chatMessagesPerMonth.</param>
        /// <param name="monitoredWallets">monitoredWallets.</param>
        /// <param name="walletWebhooksPerOrg">walletWebhooksPerOrg.</param>
        /// <param name="apiKeysPerProject">apiKeysPerProject.</param>
        /// <param name="webhooksPerProject">webhooksPerProject.</param>
        /// <param name="functionsPerProject">functionsPerProject.</param>
        /// <param name="functionInvocationsPerMonth">functionInvocationsPerMonth.</param>
        /// <param name="messagingMessagesPerMonth">messagingMessagesPerMonth.</param>
        /// <param name="smsPerMonth">smsPerMonth.</param>
        /// <param name="chatChannelsPerProject">chatChannelsPerProject.</param>
        /// <param name="backupsPerProject">backupsPerProject.</param>
        /// <param name="restoresPerMonth">restoresPerMonth.</param>
        /// <param name="integrationsPerProject">integrationsPerProject.</param>
        /// <param name="rolesPerOrg">rolesPerOrg.</param>
        /// <param name="alertsPerProject">alertsPerProject.</param>
        /// <param name="blockchainChains">blockchainChains.</param>
        /// <param name="teamUsers">teamUsers.</param>
        /// <param name="bugAnalysis">bugAnalysis.</param>
        public AdminOrgLimitsPatchRequest(int? projects = default, int? storage = default, int? bandwidth = default, int? apiCalls = default, int? buckets = default, int? collections = default, int? realtimeConnections = default, int? realtimeMessages = default, int? chatMessagesPerMonth = default, int? monitoredWallets = default, int? walletWebhooksPerOrg = default, int? apiKeysPerProject = default, int? webhooksPerProject = default, int? functionsPerProject = default, int? functionInvocationsPerMonth = default, int? messagingMessagesPerMonth = default, int? smsPerMonth = default, int? chatChannelsPerProject = default, int? backupsPerProject = default, int? restoresPerMonth = default, int? integrationsPerProject = default, int? rolesPerOrg = default, int? alertsPerProject = default, int? blockchainChains = default, int? teamUsers = default, AdminOrgLimitsPatchRequestBugAnalysis bugAnalysis = default)
        {
            this.Projects = projects;
            this.Storage = storage;
            this.Bandwidth = bandwidth;
            this.ApiCalls = apiCalls;
            this.Buckets = buckets;
            this.Collections = collections;
            this.RealtimeConnections = realtimeConnections;
            this.RealtimeMessages = realtimeMessages;
            this.ChatMessagesPerMonth = chatMessagesPerMonth;
            this.MonitoredWallets = monitoredWallets;
            this.WalletWebhooksPerOrg = walletWebhooksPerOrg;
            this.ApiKeysPerProject = apiKeysPerProject;
            this.WebhooksPerProject = webhooksPerProject;
            this.FunctionsPerProject = functionsPerProject;
            this.FunctionInvocationsPerMonth = functionInvocationsPerMonth;
            this.MessagingMessagesPerMonth = messagingMessagesPerMonth;
            this.SmsPerMonth = smsPerMonth;
            this.ChatChannelsPerProject = chatChannelsPerProject;
            this.BackupsPerProject = backupsPerProject;
            this.RestoresPerMonth = restoresPerMonth;
            this.IntegrationsPerProject = integrationsPerProject;
            this.RolesPerOrg = rolesPerOrg;
            this.AlertsPerProject = alertsPerProject;
            this.BlockchainChains = blockchainChains;
            this.TeamUsers = teamUsers;
            this.BugAnalysis = bugAnalysis;
        }

        /// <summary>
        /// Gets or Sets Projects
        /// </summary>
        [DataMember(Name = "projects", EmitDefaultValue = true)]
        public int? Projects { get; set; }

        /// <summary>
        /// Gets or Sets Storage
        /// </summary>
        [DataMember(Name = "storage", EmitDefaultValue = true)]
        public int? Storage { get; set; }

        /// <summary>
        /// Gets or Sets Bandwidth
        /// </summary>
        [DataMember(Name = "bandwidth", EmitDefaultValue = true)]
        public int? Bandwidth { get; set; }

        /// <summary>
        /// Gets or Sets ApiCalls
        /// </summary>
        [DataMember(Name = "apiCalls", EmitDefaultValue = true)]
        public int? ApiCalls { get; set; }

        /// <summary>
        /// Gets or Sets Buckets
        /// </summary>
        [DataMember(Name = "buckets", EmitDefaultValue = true)]
        public int? Buckets { get; set; }

        /// <summary>
        /// Gets or Sets Collections
        /// </summary>
        [DataMember(Name = "collections", EmitDefaultValue = true)]
        public int? Collections { get; set; }

        /// <summary>
        /// Gets or Sets RealtimeConnections
        /// </summary>
        [DataMember(Name = "realtimeConnections", EmitDefaultValue = true)]
        public int? RealtimeConnections { get; set; }

        /// <summary>
        /// Gets or Sets RealtimeMessages
        /// </summary>
        [DataMember(Name = "realtimeMessages", EmitDefaultValue = true)]
        public int? RealtimeMessages { get; set; }

        /// <summary>
        /// Gets or Sets ChatMessagesPerMonth
        /// </summary>
        [DataMember(Name = "chatMessagesPerMonth", EmitDefaultValue = true)]
        public int? ChatMessagesPerMonth { get; set; }

        /// <summary>
        /// Gets or Sets MonitoredWallets
        /// </summary>
        [DataMember(Name = "monitoredWallets", EmitDefaultValue = true)]
        public int? MonitoredWallets { get; set; }

        /// <summary>
        /// Gets or Sets WalletWebhooksPerOrg
        /// </summary>
        [DataMember(Name = "walletWebhooksPerOrg", EmitDefaultValue = true)]
        public int? WalletWebhooksPerOrg { get; set; }

        /// <summary>
        /// Gets or Sets ApiKeysPerProject
        /// </summary>
        [DataMember(Name = "apiKeysPerProject", EmitDefaultValue = true)]
        public int? ApiKeysPerProject { get; set; }

        /// <summary>
        /// Gets or Sets WebhooksPerProject
        /// </summary>
        [DataMember(Name = "webhooksPerProject", EmitDefaultValue = true)]
        public int? WebhooksPerProject { get; set; }

        /// <summary>
        /// Gets or Sets FunctionsPerProject
        /// </summary>
        [DataMember(Name = "functionsPerProject", EmitDefaultValue = true)]
        public int? FunctionsPerProject { get; set; }

        /// <summary>
        /// Gets or Sets FunctionInvocationsPerMonth
        /// </summary>
        [DataMember(Name = "functionInvocationsPerMonth", EmitDefaultValue = true)]
        public int? FunctionInvocationsPerMonth { get; set; }

        /// <summary>
        /// Gets or Sets MessagingMessagesPerMonth
        /// </summary>
        [DataMember(Name = "messagingMessagesPerMonth", EmitDefaultValue = true)]
        public int? MessagingMessagesPerMonth { get; set; }

        /// <summary>
        /// Gets or Sets SmsPerMonth
        /// </summary>
        [DataMember(Name = "smsPerMonth", EmitDefaultValue = true)]
        public int? SmsPerMonth { get; set; }

        /// <summary>
        /// Gets or Sets ChatChannelsPerProject
        /// </summary>
        [DataMember(Name = "chatChannelsPerProject", EmitDefaultValue = true)]
        public int? ChatChannelsPerProject { get; set; }

        /// <summary>
        /// Gets or Sets BackupsPerProject
        /// </summary>
        [DataMember(Name = "backupsPerProject", EmitDefaultValue = true)]
        public int? BackupsPerProject { get; set; }

        /// <summary>
        /// Gets or Sets RestoresPerMonth
        /// </summary>
        [DataMember(Name = "restoresPerMonth", EmitDefaultValue = true)]
        public int? RestoresPerMonth { get; set; }

        /// <summary>
        /// Gets or Sets IntegrationsPerProject
        /// </summary>
        [DataMember(Name = "integrationsPerProject", EmitDefaultValue = true)]
        public int? IntegrationsPerProject { get; set; }

        /// <summary>
        /// Gets or Sets RolesPerOrg
        /// </summary>
        [DataMember(Name = "rolesPerOrg", EmitDefaultValue = true)]
        public int? RolesPerOrg { get; set; }

        /// <summary>
        /// Gets or Sets AlertsPerProject
        /// </summary>
        [DataMember(Name = "alertsPerProject", EmitDefaultValue = true)]
        public int? AlertsPerProject { get; set; }

        /// <summary>
        /// Gets or Sets BlockchainChains
        /// </summary>
        [DataMember(Name = "blockchainChains", EmitDefaultValue = true)]
        public int? BlockchainChains { get; set; }

        /// <summary>
        /// Gets or Sets TeamUsers
        /// </summary>
        [DataMember(Name = "teamUsers", EmitDefaultValue = true)]
        public int? TeamUsers { get; set; }

        /// <summary>
        /// Gets or Sets BugAnalysis
        /// </summary>
        [DataMember(Name = "bugAnalysis", EmitDefaultValue = false)]
        public AdminOrgLimitsPatchRequestBugAnalysis BugAnalysis { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdminOrgLimitsPatchRequest {\n");
            sb.Append("  Projects: ").Append(Projects).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  Bandwidth: ").Append(Bandwidth).Append("\n");
            sb.Append("  ApiCalls: ").Append(ApiCalls).Append("\n");
            sb.Append("  Buckets: ").Append(Buckets).Append("\n");
            sb.Append("  Collections: ").Append(Collections).Append("\n");
            sb.Append("  RealtimeConnections: ").Append(RealtimeConnections).Append("\n");
            sb.Append("  RealtimeMessages: ").Append(RealtimeMessages).Append("\n");
            sb.Append("  ChatMessagesPerMonth: ").Append(ChatMessagesPerMonth).Append("\n");
            sb.Append("  MonitoredWallets: ").Append(MonitoredWallets).Append("\n");
            sb.Append("  WalletWebhooksPerOrg: ").Append(WalletWebhooksPerOrg).Append("\n");
            sb.Append("  ApiKeysPerProject: ").Append(ApiKeysPerProject).Append("\n");
            sb.Append("  WebhooksPerProject: ").Append(WebhooksPerProject).Append("\n");
            sb.Append("  FunctionsPerProject: ").Append(FunctionsPerProject).Append("\n");
            sb.Append("  FunctionInvocationsPerMonth: ").Append(FunctionInvocationsPerMonth).Append("\n");
            sb.Append("  MessagingMessagesPerMonth: ").Append(MessagingMessagesPerMonth).Append("\n");
            sb.Append("  SmsPerMonth: ").Append(SmsPerMonth).Append("\n");
            sb.Append("  ChatChannelsPerProject: ").Append(ChatChannelsPerProject).Append("\n");
            sb.Append("  BackupsPerProject: ").Append(BackupsPerProject).Append("\n");
            sb.Append("  RestoresPerMonth: ").Append(RestoresPerMonth).Append("\n");
            sb.Append("  IntegrationsPerProject: ").Append(IntegrationsPerProject).Append("\n");
            sb.Append("  RolesPerOrg: ").Append(RolesPerOrg).Append("\n");
            sb.Append("  AlertsPerProject: ").Append(AlertsPerProject).Append("\n");
            sb.Append("  BlockchainChains: ").Append(BlockchainChains).Append("\n");
            sb.Append("  TeamUsers: ").Append(TeamUsers).Append("\n");
            sb.Append("  BugAnalysis: ").Append(BugAnalysis).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Projects (int?) minimum
            if (this.Projects < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Projects, must be a value greater than or equal to 0.", new [] { "Projects" });
            }

            // Storage (int?) minimum
            if (this.Storage < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Storage, must be a value greater than or equal to 0.", new [] { "Storage" });
            }

            // Bandwidth (int?) minimum
            if (this.Bandwidth < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Bandwidth, must be a value greater than or equal to 0.", new [] { "Bandwidth" });
            }

            // ApiCalls (int?) minimum
            if (this.ApiCalls < (int?)0)
            {
                yield return new ValidationResult("Invalid value for ApiCalls, must be a value greater than or equal to 0.", new [] { "ApiCalls" });
            }

            // Buckets (int?) minimum
            if (this.Buckets < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Buckets, must be a value greater than or equal to 0.", new [] { "Buckets" });
            }

            // Collections (int?) minimum
            if (this.Collections < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Collections, must be a value greater than or equal to 0.", new [] { "Collections" });
            }

            // RealtimeConnections (int?) minimum
            if (this.RealtimeConnections < (int?)0)
            {
                yield return new ValidationResult("Invalid value for RealtimeConnections, must be a value greater than or equal to 0.", new [] { "RealtimeConnections" });
            }

            // RealtimeMessages (int?) minimum
            if (this.RealtimeMessages < (int?)0)
            {
                yield return new ValidationResult("Invalid value for RealtimeMessages, must be a value greater than or equal to 0.", new [] { "RealtimeMessages" });
            }

            // ChatMessagesPerMonth (int?) minimum
            if (this.ChatMessagesPerMonth < (int?)0)
            {
                yield return new ValidationResult("Invalid value for ChatMessagesPerMonth, must be a value greater than or equal to 0.", new [] { "ChatMessagesPerMonth" });
            }

            // MonitoredWallets (int?) minimum
            if (this.MonitoredWallets < (int?)0)
            {
                yield return new ValidationResult("Invalid value for MonitoredWallets, must be a value greater than or equal to 0.", new [] { "MonitoredWallets" });
            }

            // WalletWebhooksPerOrg (int?) minimum
            if (this.WalletWebhooksPerOrg < (int?)0)
            {
                yield return new ValidationResult("Invalid value for WalletWebhooksPerOrg, must be a value greater than or equal to 0.", new [] { "WalletWebhooksPerOrg" });
            }

            // ApiKeysPerProject (int?) minimum
            if (this.ApiKeysPerProject < (int?)0)
            {
                yield return new ValidationResult("Invalid value for ApiKeysPerProject, must be a value greater than or equal to 0.", new [] { "ApiKeysPerProject" });
            }

            // WebhooksPerProject (int?) minimum
            if (this.WebhooksPerProject < (int?)0)
            {
                yield return new ValidationResult("Invalid value for WebhooksPerProject, must be a value greater than or equal to 0.", new [] { "WebhooksPerProject" });
            }

            // FunctionsPerProject (int?) minimum
            if (this.FunctionsPerProject < (int?)0)
            {
                yield return new ValidationResult("Invalid value for FunctionsPerProject, must be a value greater than or equal to 0.", new [] { "FunctionsPerProject" });
            }

            // FunctionInvocationsPerMonth (int?) minimum
            if (this.FunctionInvocationsPerMonth < (int?)0)
            {
                yield return new ValidationResult("Invalid value for FunctionInvocationsPerMonth, must be a value greater than or equal to 0.", new [] { "FunctionInvocationsPerMonth" });
            }

            // MessagingMessagesPerMonth (int?) minimum
            if (this.MessagingMessagesPerMonth < (int?)0)
            {
                yield return new ValidationResult("Invalid value for MessagingMessagesPerMonth, must be a value greater than or equal to 0.", new [] { "MessagingMessagesPerMonth" });
            }

            // SmsPerMonth (int?) minimum
            if (this.SmsPerMonth < (int?)0)
            {
                yield return new ValidationResult("Invalid value for SmsPerMonth, must be a value greater than or equal to 0.", new [] { "SmsPerMonth" });
            }

            // ChatChannelsPerProject (int?) minimum
            if (this.ChatChannelsPerProject < (int?)0)
            {
                yield return new ValidationResult("Invalid value for ChatChannelsPerProject, must be a value greater than or equal to 0.", new [] { "ChatChannelsPerProject" });
            }

            // BackupsPerProject (int?) minimum
            if (this.BackupsPerProject < (int?)0)
            {
                yield return new ValidationResult("Invalid value for BackupsPerProject, must be a value greater than or equal to 0.", new [] { "BackupsPerProject" });
            }

            // RestoresPerMonth (int?) minimum
            if (this.RestoresPerMonth < (int?)0)
            {
                yield return new ValidationResult("Invalid value for RestoresPerMonth, must be a value greater than or equal to 0.", new [] { "RestoresPerMonth" });
            }

            // IntegrationsPerProject (int?) minimum
            if (this.IntegrationsPerProject < (int?)0)
            {
                yield return new ValidationResult("Invalid value for IntegrationsPerProject, must be a value greater than or equal to 0.", new [] { "IntegrationsPerProject" });
            }

            // RolesPerOrg (int?) minimum
            if (this.RolesPerOrg < (int?)0)
            {
                yield return new ValidationResult("Invalid value for RolesPerOrg, must be a value greater than or equal to 0.", new [] { "RolesPerOrg" });
            }

            // AlertsPerProject (int?) minimum
            if (this.AlertsPerProject < (int?)0)
            {
                yield return new ValidationResult("Invalid value for AlertsPerProject, must be a value greater than or equal to 0.", new [] { "AlertsPerProject" });
            }

            // BlockchainChains (int?) minimum
            if (this.BlockchainChains < (int?)0)
            {
                yield return new ValidationResult("Invalid value for BlockchainChains, must be a value greater than or equal to 0.", new [] { "BlockchainChains" });
            }

            // TeamUsers (int?) minimum
            if (this.TeamUsers < (int?)0)
            {
                yield return new ValidationResult("Invalid value for TeamUsers, must be a value greater than or equal to 0.", new [] { "TeamUsers" });
            }

            yield break;
        }
    }

}
