// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.7
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// ChatList200ResponseDataChatsInnerLastMessage
    /// </summary>
    public partial class ChatList200ResponseDataChatsInnerLastMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChatList200ResponseDataChatsInnerLastMessage" /> class.
        /// </summary>
        /// <param name="content">content</param>
        [JsonConstructor]
        public ChatList200ResponseDataChatsInnerLastMessage(Option<string?> content = default)
        {
            ContentOption = content;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Content
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [JsonPropertyName("content")]
        public string? Content { get { return this.ContentOption; } set { this.ContentOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChatList200ResponseDataChatsInnerLastMessage {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChatList200ResponseDataChatsInnerLastMessage" />
    /// </summary>
    public class ChatList200ResponseDataChatsInnerLastMessageJsonConverter : JsonConverter<ChatList200ResponseDataChatsInnerLastMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChatList200ResponseDataChatsInnerLastMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChatList200ResponseDataChatsInnerLastMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> content = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "content":
                            content = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class ChatList200ResponseDataChatsInnerLastMessage.");

            return new ChatList200ResponseDataChatsInnerLastMessage(content);
        }

        /// <summary>
        /// Serializes a <see cref="ChatList200ResponseDataChatsInnerLastMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="chatList200ResponseDataChatsInnerLastMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChatList200ResponseDataChatsInnerLastMessage chatList200ResponseDataChatsInnerLastMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, chatList200ResponseDataChatsInnerLastMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChatList200ResponseDataChatsInnerLastMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="chatList200ResponseDataChatsInnerLastMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChatList200ResponseDataChatsInnerLastMessage chatList200ResponseDataChatsInnerLastMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (chatList200ResponseDataChatsInnerLastMessage.ContentOption.IsSet && chatList200ResponseDataChatsInnerLastMessage.Content == null)
                throw new ArgumentNullException(nameof(chatList200ResponseDataChatsInnerLastMessage.Content), "Property is required for class ChatList200ResponseDataChatsInnerLastMessage.");

            if (chatList200ResponseDataChatsInnerLastMessage.ContentOption.IsSet)
                writer.WriteString("content", chatList200ResponseDataChatsInnerLastMessage.Content);
        }
    }
}
