// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// CheckPermissions200ResponsePermissions
    /// </summary>
    public partial class CheckPermissions200ResponsePermissions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckPermissions200ResponsePermissions" /> class.
        /// </summary>
        /// <param name="system">system</param>
        /// <param name="custom">custom</param>
        /// <param name="combined">combined</param>
        [JsonConstructor]
        public CheckPermissions200ResponsePermissions(Option<List<string>?> @system = default, Option<List<string>?> custom = default, Option<List<string>?> combined = default)
        {
            SystemOption = @system;
            CustomOption = custom;
            CombinedOption = combined;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of System
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> SystemOption { get; private set; }

        /// <summary>
        /// Gets or Sets System
        /// </summary>
        [JsonPropertyName("system")]
        public List<string>? System { get { return this.SystemOption; } set { this.SystemOption = new(value); } }

        /// <summary>
        /// Used to track the state of Custom
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> CustomOption { get; private set; }

        /// <summary>
        /// Gets or Sets Custom
        /// </summary>
        [JsonPropertyName("custom")]
        public List<string>? Custom { get { return this.CustomOption; } set { this.CustomOption = new(value); } }

        /// <summary>
        /// Used to track the state of Combined
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> CombinedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Combined
        /// </summary>
        [JsonPropertyName("combined")]
        public List<string>? Combined { get { return this.CombinedOption; } set { this.CombinedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckPermissions200ResponsePermissions {\n");
            sb.Append("  System: ").Append(System).Append("\n");
            sb.Append("  Custom: ").Append(Custom).Append("\n");
            sb.Append("  Combined: ").Append(Combined).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CheckPermissions200ResponsePermissions" />
    /// </summary>
    public class CheckPermissions200ResponsePermissionsJsonConverter : JsonConverter<CheckPermissions200ResponsePermissions>
    {
        /// <summary>
        /// Deserializes json to <see cref="CheckPermissions200ResponsePermissions" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CheckPermissions200ResponsePermissions Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> varSystem = default;
            Option<List<string>?> custom = default;
            Option<List<string>?> combined = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "system":
                            varSystem = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "custom":
                            custom = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "combined":
                            combined = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (varSystem.IsSet && varSystem.Value == null)
                throw new ArgumentNullException(nameof(varSystem), "Property is not nullable for class CheckPermissions200ResponsePermissions.");

            if (custom.IsSet && custom.Value == null)
                throw new ArgumentNullException(nameof(custom), "Property is not nullable for class CheckPermissions200ResponsePermissions.");

            if (combined.IsSet && combined.Value == null)
                throw new ArgumentNullException(nameof(combined), "Property is not nullable for class CheckPermissions200ResponsePermissions.");

            return new CheckPermissions200ResponsePermissions(varSystem, custom, combined);
        }

        /// <summary>
        /// Serializes a <see cref="CheckPermissions200ResponsePermissions" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkPermissions200ResponsePermissions"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CheckPermissions200ResponsePermissions checkPermissions200ResponsePermissions, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, checkPermissions200ResponsePermissions, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CheckPermissions200ResponsePermissions" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkPermissions200ResponsePermissions"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CheckPermissions200ResponsePermissions checkPermissions200ResponsePermissions, JsonSerializerOptions jsonSerializerOptions)
        {
            if (checkPermissions200ResponsePermissions.SystemOption.IsSet && checkPermissions200ResponsePermissions.System == null)
                throw new ArgumentNullException(nameof(checkPermissions200ResponsePermissions.System), "Property is required for class CheckPermissions200ResponsePermissions.");

            if (checkPermissions200ResponsePermissions.CustomOption.IsSet && checkPermissions200ResponsePermissions.Custom == null)
                throw new ArgumentNullException(nameof(checkPermissions200ResponsePermissions.Custom), "Property is required for class CheckPermissions200ResponsePermissions.");

            if (checkPermissions200ResponsePermissions.CombinedOption.IsSet && checkPermissions200ResponsePermissions.Combined == null)
                throw new ArgumentNullException(nameof(checkPermissions200ResponsePermissions.Combined), "Property is required for class CheckPermissions200ResponsePermissions.");

            if (checkPermissions200ResponsePermissions.SystemOption.IsSet)
            {
                writer.WritePropertyName("system");
                JsonSerializer.Serialize(writer, checkPermissions200ResponsePermissions.System, jsonSerializerOptions);
            }
            if (checkPermissions200ResponsePermissions.CustomOption.IsSet)
            {
                writer.WritePropertyName("custom");
                JsonSerializer.Serialize(writer, checkPermissions200ResponsePermissions.Custom, jsonSerializerOptions);
            }
            if (checkPermissions200ResponsePermissions.CombinedOption.IsSet)
            {
                writer.WritePropertyName("combined");
                JsonSerializer.Serialize(writer, checkPermissions200ResponsePermissions.Combined, jsonSerializerOptions);
            }
        }
    }
}
