// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave for fiat (platform subscriptions and payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.12
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// FunctionsGetVersions200ResponseData
    /// </summary>
    public partial class FunctionsGetVersions200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FunctionsGetVersions200ResponseData" /> class.
        /// </summary>
        /// <param name="versions">versions</param>
        [JsonConstructor]
        public FunctionsGetVersions200ResponseData(Option<List<FunctionsGetVersions200ResponseDataVersionsInner>?> versions = default)
        {
            VersionsOption = versions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Versions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<FunctionsGetVersions200ResponseDataVersionsInner>?> VersionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Versions
        /// </summary>
        [JsonPropertyName("versions")]
        public List<FunctionsGetVersions200ResponseDataVersionsInner>? Versions { get { return this.VersionsOption; } set { this.VersionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FunctionsGetVersions200ResponseData {\n");
            sb.Append("  Versions: ").Append(Versions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FunctionsGetVersions200ResponseData" />
    /// </summary>
    public class FunctionsGetVersions200ResponseDataJsonConverter : JsonConverter<FunctionsGetVersions200ResponseData>
    {
        /// <summary>
        /// Deserializes json to <see cref="FunctionsGetVersions200ResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FunctionsGetVersions200ResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<FunctionsGetVersions200ResponseDataVersionsInner>?> versions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "versions":
                            versions = new Option<List<FunctionsGetVersions200ResponseDataVersionsInner>?>(JsonSerializer.Deserialize<List<FunctionsGetVersions200ResponseDataVersionsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (versions.IsSet && versions.Value == null)
                throw new ArgumentNullException(nameof(versions), "Property is not nullable for class FunctionsGetVersions200ResponseData.");

            return new FunctionsGetVersions200ResponseData(versions);
        }

        /// <summary>
        /// Serializes a <see cref="FunctionsGetVersions200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="functionsGetVersions200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FunctionsGetVersions200ResponseData functionsGetVersions200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, functionsGetVersions200ResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FunctionsGetVersions200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="functionsGetVersions200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FunctionsGetVersions200ResponseData functionsGetVersions200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (functionsGetVersions200ResponseData.VersionsOption.IsSet && functionsGetVersions200ResponseData.Versions == null)
                throw new ArgumentNullException(nameof(functionsGetVersions200ResponseData.Versions), "Property is required for class FunctionsGetVersions200ResponseData.");

            if (functionsGetVersions200ResponseData.VersionsOption.IsSet)
            {
                writer.WritePropertyName("versions");
                JsonSerializer.Serialize(writer, functionsGetVersions200ResponseData.Versions, jsonSerializerOptions);
            }
        }
    }
}
