// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// GetActiveUsers200ResponseUsersInner
    /// </summary>
    public partial class GetActiveUsers200ResponseUsersInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetActiveUsers200ResponseUsersInner" /> class.
        /// </summary>
        /// <param name="userId">userId</param>
        /// <param name="connectedAt">connectedAt</param>
        /// <param name="socketId">socketId</param>
        [JsonConstructor]
        public GetActiveUsers200ResponseUsersInner(Option<string?> userId = default, Option<DateTime?> connectedAt = default, Option<string?> socketId = default)
        {
            UserIdOption = userId;
            ConnectedAtOption = connectedAt;
            SocketIdOption = socketId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("userId")]
        public string? UserId { get { return this.UserIdOption; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConnectedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ConnectedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConnectedAt
        /// </summary>
        [JsonPropertyName("connectedAt")]
        public DateTime? ConnectedAt { get { return this.ConnectedAtOption; } set { this.ConnectedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of SocketId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SocketIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SocketId
        /// </summary>
        [JsonPropertyName("socketId")]
        public string? SocketId { get { return this.SocketIdOption; } set { this.SocketIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetActiveUsers200ResponseUsersInner {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  ConnectedAt: ").Append(ConnectedAt).Append("\n");
            sb.Append("  SocketId: ").Append(SocketId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetActiveUsers200ResponseUsersInner" />
    /// </summary>
    public class GetActiveUsers200ResponseUsersInnerJsonConverter : JsonConverter<GetActiveUsers200ResponseUsersInner>
    {
        /// <summary>
        /// The format to use to serialize ConnectedAt
        /// </summary>
        public static string ConnectedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GetActiveUsers200ResponseUsersInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetActiveUsers200ResponseUsersInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> userId = default;
            Option<DateTime?> connectedAt = default;
            Option<string?> socketId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "userId":
                            userId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "connectedAt":
                            connectedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "socketId":
                            socketId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class GetActiveUsers200ResponseUsersInner.");

            if (connectedAt.IsSet && connectedAt.Value == null)
                throw new ArgumentNullException(nameof(connectedAt), "Property is not nullable for class GetActiveUsers200ResponseUsersInner.");

            if (socketId.IsSet && socketId.Value == null)
                throw new ArgumentNullException(nameof(socketId), "Property is not nullable for class GetActiveUsers200ResponseUsersInner.");

            return new GetActiveUsers200ResponseUsersInner(userId, connectedAt, socketId);
        }

        /// <summary>
        /// Serializes a <see cref="GetActiveUsers200ResponseUsersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getActiveUsers200ResponseUsersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetActiveUsers200ResponseUsersInner getActiveUsers200ResponseUsersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getActiveUsers200ResponseUsersInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetActiveUsers200ResponseUsersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getActiveUsers200ResponseUsersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetActiveUsers200ResponseUsersInner getActiveUsers200ResponseUsersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getActiveUsers200ResponseUsersInner.UserIdOption.IsSet && getActiveUsers200ResponseUsersInner.UserId == null)
                throw new ArgumentNullException(nameof(getActiveUsers200ResponseUsersInner.UserId), "Property is required for class GetActiveUsers200ResponseUsersInner.");

            if (getActiveUsers200ResponseUsersInner.SocketIdOption.IsSet && getActiveUsers200ResponseUsersInner.SocketId == null)
                throw new ArgumentNullException(nameof(getActiveUsers200ResponseUsersInner.SocketId), "Property is required for class GetActiveUsers200ResponseUsersInner.");

            if (getActiveUsers200ResponseUsersInner.UserIdOption.IsSet)
                writer.WriteString("userId", getActiveUsers200ResponseUsersInner.UserId);

            if (getActiveUsers200ResponseUsersInner.ConnectedAtOption.IsSet)
                writer.WriteString("connectedAt", getActiveUsers200ResponseUsersInner.ConnectedAtOption.Value!.Value.ToString(ConnectedAtFormat));

            if (getActiveUsers200ResponseUsersInner.SocketIdOption.IsSet)
                writer.WriteString("socketId", getActiveUsers200ResponseUsersInner.SocketId);
        }
    }
}
