// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// GetMultiRoleConfig200ResponseData
    /// </summary>
    public partial class GetMultiRoleConfig200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMultiRoleConfig200ResponseData" /> class.
        /// </summary>
        /// <param name="isEnabled">isEnabled</param>
        /// <param name="defaultRole">defaultRole</param>
        /// <param name="settings">settings</param>
        /// <param name="roles">roles</param>
        [JsonConstructor]
        public GetMultiRoleConfig200ResponseData(Option<bool?> isEnabled = default, Option<string?> defaultRole = default, Option<Object?> settings = default, Option<List<Object>?> roles = default)
        {
            IsEnabledOption = isEnabled;
            DefaultRoleOption = defaultRole;
            SettingsOption = settings;
            RolesOption = roles;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IsEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsEnabled
        /// </summary>
        [JsonPropertyName("isEnabled")]
        public bool? IsEnabled { get { return this.IsEnabledOption; } set { this.IsEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of DefaultRole
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DefaultRoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets DefaultRole
        /// </summary>
        [JsonPropertyName("defaultRole")]
        public string? DefaultRole { get { return this.DefaultRoleOption; } set { this.DefaultRoleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Settings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> SettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [JsonPropertyName("settings")]
        public Object? Settings { get { return this.SettingsOption; } set { this.SettingsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Roles
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>?> RolesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Roles
        /// </summary>
        [JsonPropertyName("roles")]
        public List<Object>? Roles { get { return this.RolesOption; } set { this.RolesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMultiRoleConfig200ResponseData {\n");
            sb.Append("  IsEnabled: ").Append(IsEnabled).Append("\n");
            sb.Append("  DefaultRole: ").Append(DefaultRole).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetMultiRoleConfig200ResponseData" />
    /// </summary>
    public class GetMultiRoleConfig200ResponseDataJsonConverter : JsonConverter<GetMultiRoleConfig200ResponseData>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetMultiRoleConfig200ResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetMultiRoleConfig200ResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isEnabled = default;
            Option<string?> defaultRole = default;
            Option<Object?> settings = default;
            Option<List<Object>?> roles = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "isEnabled":
                            isEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "defaultRole":
                            defaultRole = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "settings":
                            settings = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "roles":
                            roles = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (isEnabled.IsSet && isEnabled.Value == null)
                throw new ArgumentNullException(nameof(isEnabled), "Property is not nullable for class GetMultiRoleConfig200ResponseData.");

            if (defaultRole.IsSet && defaultRole.Value == null)
                throw new ArgumentNullException(nameof(defaultRole), "Property is not nullable for class GetMultiRoleConfig200ResponseData.");

            if (settings.IsSet && settings.Value == null)
                throw new ArgumentNullException(nameof(settings), "Property is not nullable for class GetMultiRoleConfig200ResponseData.");

            if (roles.IsSet && roles.Value == null)
                throw new ArgumentNullException(nameof(roles), "Property is not nullable for class GetMultiRoleConfig200ResponseData.");

            return new GetMultiRoleConfig200ResponseData(isEnabled, defaultRole, settings, roles);
        }

        /// <summary>
        /// Serializes a <see cref="GetMultiRoleConfig200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMultiRoleConfig200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetMultiRoleConfig200ResponseData getMultiRoleConfig200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getMultiRoleConfig200ResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetMultiRoleConfig200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMultiRoleConfig200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetMultiRoleConfig200ResponseData getMultiRoleConfig200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getMultiRoleConfig200ResponseData.DefaultRoleOption.IsSet && getMultiRoleConfig200ResponseData.DefaultRole == null)
                throw new ArgumentNullException(nameof(getMultiRoleConfig200ResponseData.DefaultRole), "Property is required for class GetMultiRoleConfig200ResponseData.");

            if (getMultiRoleConfig200ResponseData.SettingsOption.IsSet && getMultiRoleConfig200ResponseData.Settings == null)
                throw new ArgumentNullException(nameof(getMultiRoleConfig200ResponseData.Settings), "Property is required for class GetMultiRoleConfig200ResponseData.");

            if (getMultiRoleConfig200ResponseData.RolesOption.IsSet && getMultiRoleConfig200ResponseData.Roles == null)
                throw new ArgumentNullException(nameof(getMultiRoleConfig200ResponseData.Roles), "Property is required for class GetMultiRoleConfig200ResponseData.");

            if (getMultiRoleConfig200ResponseData.IsEnabledOption.IsSet)
                writer.WriteBoolean("isEnabled", getMultiRoleConfig200ResponseData.IsEnabledOption.Value!.Value);

            if (getMultiRoleConfig200ResponseData.DefaultRoleOption.IsSet)
                writer.WriteString("defaultRole", getMultiRoleConfig200ResponseData.DefaultRole);

            if (getMultiRoleConfig200ResponseData.SettingsOption.IsSet)
            {
                writer.WritePropertyName("settings");
                JsonSerializer.Serialize(writer, getMultiRoleConfig200ResponseData.Settings, jsonSerializerOptions);
            }
            if (getMultiRoleConfig200ResponseData.RolesOption.IsSet)
            {
                writer.WritePropertyName("roles");
                JsonSerializer.Serialize(writer, getMultiRoleConfig200ResponseData.Roles, jsonSerializerOptions);
            }
        }
    }
}
