// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// GetTemplates200ResponseTemplatesInner
    /// </summary>
    public partial class GetTemplates200ResponseTemplatesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTemplates200ResponseTemplatesInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="provider">provider</param>
        /// <param name="description">description</param>
        [JsonConstructor]
        public GetTemplates200ResponseTemplatesInner(Option<string?> id = default, Option<string?> name = default, Option<string?> provider = default, Option<string?> description = default)
        {
            IdOption = id;
            NameOption = name;
            ProviderOption = provider;
            DescriptionOption = description;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("_id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Provider
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProviderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [JsonPropertyName("provider")]
        public string? Provider { get { return this.ProviderOption; } set { this.ProviderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetTemplates200ResponseTemplatesInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetTemplates200ResponseTemplatesInner" />
    /// </summary>
    public class GetTemplates200ResponseTemplatesInnerJsonConverter : JsonConverter<GetTemplates200ResponseTemplatesInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetTemplates200ResponseTemplatesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetTemplates200ResponseTemplatesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> name = default;
            Option<string?> provider = default;
            Option<string?> description = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "_id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "provider":
                            provider = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class GetTemplates200ResponseTemplatesInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class GetTemplates200ResponseTemplatesInner.");

            if (provider.IsSet && provider.Value == null)
                throw new ArgumentNullException(nameof(provider), "Property is not nullable for class GetTemplates200ResponseTemplatesInner.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class GetTemplates200ResponseTemplatesInner.");

            return new GetTemplates200ResponseTemplatesInner(id, name, provider, description);
        }

        /// <summary>
        /// Serializes a <see cref="GetTemplates200ResponseTemplatesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getTemplates200ResponseTemplatesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetTemplates200ResponseTemplatesInner getTemplates200ResponseTemplatesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getTemplates200ResponseTemplatesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetTemplates200ResponseTemplatesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getTemplates200ResponseTemplatesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetTemplates200ResponseTemplatesInner getTemplates200ResponseTemplatesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getTemplates200ResponseTemplatesInner.IdOption.IsSet && getTemplates200ResponseTemplatesInner.Id == null)
                throw new ArgumentNullException(nameof(getTemplates200ResponseTemplatesInner.Id), "Property is required for class GetTemplates200ResponseTemplatesInner.");

            if (getTemplates200ResponseTemplatesInner.NameOption.IsSet && getTemplates200ResponseTemplatesInner.Name == null)
                throw new ArgumentNullException(nameof(getTemplates200ResponseTemplatesInner.Name), "Property is required for class GetTemplates200ResponseTemplatesInner.");

            if (getTemplates200ResponseTemplatesInner.ProviderOption.IsSet && getTemplates200ResponseTemplatesInner.Provider == null)
                throw new ArgumentNullException(nameof(getTemplates200ResponseTemplatesInner.Provider), "Property is required for class GetTemplates200ResponseTemplatesInner.");

            if (getTemplates200ResponseTemplatesInner.DescriptionOption.IsSet && getTemplates200ResponseTemplatesInner.Description == null)
                throw new ArgumentNullException(nameof(getTemplates200ResponseTemplatesInner.Description), "Property is required for class GetTemplates200ResponseTemplatesInner.");

            if (getTemplates200ResponseTemplatesInner.IdOption.IsSet)
                writer.WriteString("_id", getTemplates200ResponseTemplatesInner.Id);

            if (getTemplates200ResponseTemplatesInner.NameOption.IsSet)
                writer.WriteString("name", getTemplates200ResponseTemplatesInner.Name);

            if (getTemplates200ResponseTemplatesInner.ProviderOption.IsSet)
                writer.WriteString("provider", getTemplates200ResponseTemplatesInner.Provider);

            if (getTemplates200ResponseTemplatesInner.DescriptionOption.IsSet)
                writer.WriteString("description", getTemplates200ResponseTemplatesInner.Description);
        }
    }
}
