// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// LogSecurityEvent200ResponseEvent
    /// </summary>
    public partial class LogSecurityEvent200ResponseEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogSecurityEvent200ResponseEvent" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="eventType">eventType</param>
        /// <param name="severity">severity</param>
        /// <param name="timestamp">timestamp</param>
        [JsonConstructor]
        public LogSecurityEvent200ResponseEvent(Option<string?> id = default, Option<string?> eventType = default, Option<string?> severity = default, Option<DateTime?> timestamp = default)
        {
            IdOption = id;
            EventTypeOption = eventType;
            SeverityOption = severity;
            TimestampOption = timestamp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("_id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of EventType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EventTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets EventType
        /// </summary>
        [JsonPropertyName("eventType")]
        public string? EventType { get { return this.EventTypeOption; } set { this.EventTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Severity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SeverityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [JsonPropertyName("severity")]
        public string? Severity { get { return this.SeverityOption; } set { this.SeverityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTime? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogSecurityEvent200ResponseEvent {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LogSecurityEvent200ResponseEvent" />
    /// </summary>
    public class LogSecurityEvent200ResponseEventJsonConverter : JsonConverter<LogSecurityEvent200ResponseEvent>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="LogSecurityEvent200ResponseEvent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LogSecurityEvent200ResponseEvent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> eventType = default;
            Option<string?> severity = default;
            Option<DateTime?> timestamp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "_id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "eventType":
                            eventType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "severity":
                            severity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class LogSecurityEvent200ResponseEvent.");

            if (eventType.IsSet && eventType.Value == null)
                throw new ArgumentNullException(nameof(eventType), "Property is not nullable for class LogSecurityEvent200ResponseEvent.");

            if (severity.IsSet && severity.Value == null)
                throw new ArgumentNullException(nameof(severity), "Property is not nullable for class LogSecurityEvent200ResponseEvent.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class LogSecurityEvent200ResponseEvent.");

            return new LogSecurityEvent200ResponseEvent(id, eventType, severity, timestamp);
        }

        /// <summary>
        /// Serializes a <see cref="LogSecurityEvent200ResponseEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="logSecurityEvent200ResponseEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LogSecurityEvent200ResponseEvent logSecurityEvent200ResponseEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, logSecurityEvent200ResponseEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LogSecurityEvent200ResponseEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="logSecurityEvent200ResponseEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LogSecurityEvent200ResponseEvent logSecurityEvent200ResponseEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            if (logSecurityEvent200ResponseEvent.IdOption.IsSet && logSecurityEvent200ResponseEvent.Id == null)
                throw new ArgumentNullException(nameof(logSecurityEvent200ResponseEvent.Id), "Property is required for class LogSecurityEvent200ResponseEvent.");

            if (logSecurityEvent200ResponseEvent.EventTypeOption.IsSet && logSecurityEvent200ResponseEvent.EventType == null)
                throw new ArgumentNullException(nameof(logSecurityEvent200ResponseEvent.EventType), "Property is required for class LogSecurityEvent200ResponseEvent.");

            if (logSecurityEvent200ResponseEvent.SeverityOption.IsSet && logSecurityEvent200ResponseEvent.Severity == null)
                throw new ArgumentNullException(nameof(logSecurityEvent200ResponseEvent.Severity), "Property is required for class LogSecurityEvent200ResponseEvent.");

            if (logSecurityEvent200ResponseEvent.IdOption.IsSet)
                writer.WriteString("_id", logSecurityEvent200ResponseEvent.Id);

            if (logSecurityEvent200ResponseEvent.EventTypeOption.IsSet)
                writer.WriteString("eventType", logSecurityEvent200ResponseEvent.EventType);

            if (logSecurityEvent200ResponseEvent.SeverityOption.IsSet)
                writer.WriteString("severity", logSecurityEvent200ResponseEvent.Severity);

            if (logSecurityEvent200ResponseEvent.TimestampOption.IsSet)
                writer.WriteString("timestamp", logSecurityEvent200ResponseEvent.TimestampOption.Value!.Value.ToString(TimestampFormat));
        }
    }
}
