// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.8
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// Single message record (id, type, title, body, recipients, status, sentAt).
    /// </summary>
    public partial class Message : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Message" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="title">title</param>
        /// <param name="body">body</param>
        /// <param name="subject">subject</param>
        /// <param name="recipients">recipients</param>
        /// <param name="successCount">successCount</param>
        /// <param name="failureCount">failureCount</param>
        /// <param name="status">status</param>
        /// <param name="sentAt">sentAt</param>
        [JsonConstructor]
        public Message(Option<string?> id = default, Option<TypeEnum?> type = default, Option<string?> title = default, Option<string?> body = default, Option<string?> subject = default, Option<int?> recipients = default, Option<int?> successCount = default, Option<int?> failureCount = default, Option<StatusEnum?> status = default, Option<DateTime?> sentAt = default)
        {
            IdOption = id;
            TypeOption = type;
            TitleOption = title;
            BodyOption = body;
            SubjectOption = subject;
            RecipientsOption = recipients;
            SuccessCountOption = successCount;
            FailureCountOption = failureCount;
            StatusOption = status;
            SentAtOption = sentAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Push for value: push
            /// </summary>
            Push = 1,

            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            Email = 2,

            /// <summary>
            /// Enum Sms for value: sms
            /// </summary>
            Sms = 3
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("push"))
                return TypeEnum.Push;

            if (value.Equals("email"))
                return TypeEnum.Email;

            if (value.Equals("sms"))
                return TypeEnum.Sms;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("push"))
                return TypeEnum.Push;

            if (value.Equals("email"))
                return TypeEnum.Email;

            if (value.Equals("sms"))
                return TypeEnum.Sms;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Push)
                return "push";

            if (value == TypeEnum.Email)
                return "email";

            if (value == TypeEnum.Sms)
                return "sms";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Sent for value: sent
            /// </summary>
            Sent = 1,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 2,

            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("sent"))
                return StatusEnum.Sent;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("pending"))
                return StatusEnum.Pending;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("sent"))
                return StatusEnum.Sent;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("pending"))
                return StatusEnum.Pending;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Sent)
                return "sent";

            if (value == StatusEnum.Failed)
                return "failed";

            if (value == StatusEnum.Pending)
                return "pending";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("_id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Body
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BodyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [JsonPropertyName("body")]
        public string? Body { get { return this.BodyOption; } set { this.BodyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption; } set { this.SubjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of Recipients
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RecipientsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Recipients
        /// </summary>
        [JsonPropertyName("recipients")]
        public int? Recipients { get { return this.RecipientsOption; } set { this.RecipientsOption = new(value); } }

        /// <summary>
        /// Used to track the state of SuccessCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SuccessCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuccessCount
        /// </summary>
        [JsonPropertyName("successCount")]
        public int? SuccessCount { get { return this.SuccessCountOption; } set { this.SuccessCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FailureCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureCount
        /// </summary>
        [JsonPropertyName("failureCount")]
        public int? FailureCount { get { return this.FailureCountOption; } set { this.FailureCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SentAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> SentAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets SentAt
        /// </summary>
        [JsonPropertyName("sentAt")]
        public DateTime? SentAt { get { return this.SentAtOption; } set { this.SentAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Message {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  SuccessCount: ").Append(SuccessCount).Append("\n");
            sb.Append("  FailureCount: ").Append(FailureCount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  SentAt: ").Append(SentAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Message" />
    /// </summary>
    public class MessageJsonConverter : JsonConverter<Message>
    {
        /// <summary>
        /// The format to use to serialize SentAt
        /// </summary>
        public static string SentAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Message" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Message Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<Message.TypeEnum?> type = default;
            Option<string?> title = default;
            Option<string?> body = default;
            Option<string?> subject = default;
            Option<int?> recipients = default;
            Option<int?> successCount = default;
            Option<int?> failureCount = default;
            Option<Message.StatusEnum?> status = default;
            Option<DateTime?> sentAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "_id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<Message.TypeEnum?>(Message.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "recipients":
                            recipients = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "successCount":
                            successCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "failureCount":
                            failureCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<Message.StatusEnum?>(Message.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "sentAt":
                            sentAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Message.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Message.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class Message.");

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class Message.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class Message.");

            if (recipients.IsSet && recipients.Value == null)
                throw new ArgumentNullException(nameof(recipients), "Property is not nullable for class Message.");

            if (successCount.IsSet && successCount.Value == null)
                throw new ArgumentNullException(nameof(successCount), "Property is not nullable for class Message.");

            if (failureCount.IsSet && failureCount.Value == null)
                throw new ArgumentNullException(nameof(failureCount), "Property is not nullable for class Message.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Message.");

            if (sentAt.IsSet && sentAt.Value == null)
                throw new ArgumentNullException(nameof(sentAt), "Property is not nullable for class Message.");

            return new Message(id, type, title, body, subject, recipients, successCount, failureCount, status, sentAt);
        }

        /// <summary>
        /// Serializes a <see cref="Message" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="message"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Message message, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, message, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Message" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="message"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Message message, JsonSerializerOptions jsonSerializerOptions)
        {
            if (message.IdOption.IsSet && message.Id == null)
                throw new ArgumentNullException(nameof(message.Id), "Property is required for class Message.");

            if (message.TitleOption.IsSet && message.Title == null)
                throw new ArgumentNullException(nameof(message.Title), "Property is required for class Message.");

            if (message.BodyOption.IsSet && message.Body == null)
                throw new ArgumentNullException(nameof(message.Body), "Property is required for class Message.");

            if (message.SubjectOption.IsSet && message.Subject == null)
                throw new ArgumentNullException(nameof(message.Subject), "Property is required for class Message.");

            if (message.IdOption.IsSet)
                writer.WriteString("_id", message.Id);

            var typeRawValue = Message.TypeEnumToJsonValue(message.TypeOption.Value!.Value);
            writer.WriteString("type", typeRawValue);
            if (message.TitleOption.IsSet)
                writer.WriteString("title", message.Title);

            if (message.BodyOption.IsSet)
                writer.WriteString("body", message.Body);

            if (message.SubjectOption.IsSet)
                writer.WriteString("subject", message.Subject);

            if (message.RecipientsOption.IsSet)
                writer.WriteNumber("recipients", message.RecipientsOption.Value!.Value);

            if (message.SuccessCountOption.IsSet)
                writer.WriteNumber("successCount", message.SuccessCountOption.Value!.Value);

            if (message.FailureCountOption.IsSet)
                writer.WriteNumber("failureCount", message.FailureCountOption.Value!.Value);

            var statusRawValue = Message.StatusEnumToJsonValue(message.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (message.SentAtOption.IsSet)
                writer.WriteString("sentAt", message.SentAtOption.Value!.Value.ToString(SentAtFormat));
        }
    }
}
