// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// MonitoringPerformanceResponseMetrics
    /// </summary>
    public partial class MonitoringPerformanceResponseMetrics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringPerformanceResponseMetrics" /> class.
        /// </summary>
        /// <param name="totalRequests">totalRequests</param>
        /// <param name="avgResponseTime">avgResponseTime</param>
        /// <param name="minResponseTime">minResponseTime</param>
        /// <param name="maxResponseTime">maxResponseTime</param>
        /// <param name="errorCount">errorCount</param>
        /// <param name="successCount">successCount</param>
        /// <param name="successRate">successRate</param>
        /// <param name="errorRate">errorRate</param>
        /// <param name="latencySource">usage_stat when filled from UsageStat</param>
        [JsonConstructor]
        public MonitoringPerformanceResponseMetrics(Option<int?> totalRequests = default, Option<decimal?> avgResponseTime = default, Option<decimal?> minResponseTime = default, Option<decimal?> maxResponseTime = default, Option<int?> errorCount = default, Option<int?> successCount = default, Option<decimal?> successRate = default, Option<decimal?> errorRate = default, Option<string?> latencySource = default)
        {
            TotalRequestsOption = totalRequests;
            AvgResponseTimeOption = avgResponseTime;
            MinResponseTimeOption = minResponseTime;
            MaxResponseTimeOption = maxResponseTime;
            ErrorCountOption = errorCount;
            SuccessCountOption = successCount;
            SuccessRateOption = successRate;
            ErrorRateOption = errorRate;
            LatencySourceOption = latencySource;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TotalRequests
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalRequestsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalRequests
        /// </summary>
        [JsonPropertyName("totalRequests")]
        public int? TotalRequests { get { return this.TotalRequestsOption; } set { this.TotalRequestsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AvgResponseTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AvgResponseTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AvgResponseTime
        /// </summary>
        [JsonPropertyName("avgResponseTime")]
        public decimal? AvgResponseTime { get { return this.AvgResponseTimeOption; } set { this.AvgResponseTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of MinResponseTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> MinResponseTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets MinResponseTime
        /// </summary>
        [JsonPropertyName("minResponseTime")]
        public decimal? MinResponseTime { get { return this.MinResponseTimeOption; } set { this.MinResponseTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of MaxResponseTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> MaxResponseTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets MaxResponseTime
        /// </summary>
        [JsonPropertyName("maxResponseTime")]
        public decimal? MaxResponseTime { get { return this.MaxResponseTimeOption; } set { this.MaxResponseTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ErrorCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorCount
        /// </summary>
        [JsonPropertyName("errorCount")]
        public int? ErrorCount { get { return this.ErrorCountOption; } set { this.ErrorCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SuccessCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SuccessCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuccessCount
        /// </summary>
        [JsonPropertyName("successCount")]
        public int? SuccessCount { get { return this.SuccessCountOption; } set { this.SuccessCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SuccessRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> SuccessRateOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuccessRate
        /// </summary>
        [JsonPropertyName("successRate")]
        public decimal? SuccessRate { get { return this.SuccessRateOption; } set { this.SuccessRateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ErrorRateOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorRate
        /// </summary>
        [JsonPropertyName("errorRate")]
        public decimal? ErrorRate { get { return this.ErrorRateOption; } set { this.ErrorRateOption = new(value); } }

        /// <summary>
        /// Used to track the state of LatencySource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LatencySourceOption { get; private set; }

        /// <summary>
        /// usage_stat when filled from UsageStat
        /// </summary>
        /// <value>usage_stat when filled from UsageStat</value>
        [JsonPropertyName("latencySource")]
        public string? LatencySource { get { return this.LatencySourceOption; } set { this.LatencySourceOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MonitoringPerformanceResponseMetrics {\n");
            sb.Append("  TotalRequests: ").Append(TotalRequests).Append("\n");
            sb.Append("  AvgResponseTime: ").Append(AvgResponseTime).Append("\n");
            sb.Append("  MinResponseTime: ").Append(MinResponseTime).Append("\n");
            sb.Append("  MaxResponseTime: ").Append(MaxResponseTime).Append("\n");
            sb.Append("  ErrorCount: ").Append(ErrorCount).Append("\n");
            sb.Append("  SuccessCount: ").Append(SuccessCount).Append("\n");
            sb.Append("  SuccessRate: ").Append(SuccessRate).Append("\n");
            sb.Append("  ErrorRate: ").Append(ErrorRate).Append("\n");
            sb.Append("  LatencySource: ").Append(LatencySource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MonitoringPerformanceResponseMetrics" />
    /// </summary>
    public class MonitoringPerformanceResponseMetricsJsonConverter : JsonConverter<MonitoringPerformanceResponseMetrics>
    {
        /// <summary>
        /// Deserializes json to <see cref="MonitoringPerformanceResponseMetrics" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MonitoringPerformanceResponseMetrics Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> totalRequests = default;
            Option<decimal?> avgResponseTime = default;
            Option<decimal?> minResponseTime = default;
            Option<decimal?> maxResponseTime = default;
            Option<int?> errorCount = default;
            Option<int?> successCount = default;
            Option<decimal?> successRate = default;
            Option<decimal?> errorRate = default;
            Option<string?> latencySource = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "totalRequests":
                            totalRequests = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "avgResponseTime":
                            avgResponseTime = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "minResponseTime":
                            minResponseTime = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "maxResponseTime":
                            maxResponseTime = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "errorCount":
                            errorCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "successCount":
                            successCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "successRate":
                            successRate = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "errorRate":
                            errorRate = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "latencySource":
                            latencySource = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (totalRequests.IsSet && totalRequests.Value == null)
                throw new ArgumentNullException(nameof(totalRequests), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (avgResponseTime.IsSet && avgResponseTime.Value == null)
                throw new ArgumentNullException(nameof(avgResponseTime), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (minResponseTime.IsSet && minResponseTime.Value == null)
                throw new ArgumentNullException(nameof(minResponseTime), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (maxResponseTime.IsSet && maxResponseTime.Value == null)
                throw new ArgumentNullException(nameof(maxResponseTime), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (errorCount.IsSet && errorCount.Value == null)
                throw new ArgumentNullException(nameof(errorCount), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (successCount.IsSet && successCount.Value == null)
                throw new ArgumentNullException(nameof(successCount), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (successRate.IsSet && successRate.Value == null)
                throw new ArgumentNullException(nameof(successRate), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (errorRate.IsSet && errorRate.Value == null)
                throw new ArgumentNullException(nameof(errorRate), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            if (latencySource.IsSet && latencySource.Value == null)
                throw new ArgumentNullException(nameof(latencySource), "Property is not nullable for class MonitoringPerformanceResponseMetrics.");

            return new MonitoringPerformanceResponseMetrics(totalRequests, avgResponseTime, minResponseTime, maxResponseTime, errorCount, successCount, successRate, errorRate, latencySource);
        }

        /// <summary>
        /// Serializes a <see cref="MonitoringPerformanceResponseMetrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="monitoringPerformanceResponseMetrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MonitoringPerformanceResponseMetrics monitoringPerformanceResponseMetrics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, monitoringPerformanceResponseMetrics, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MonitoringPerformanceResponseMetrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="monitoringPerformanceResponseMetrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MonitoringPerformanceResponseMetrics monitoringPerformanceResponseMetrics, JsonSerializerOptions jsonSerializerOptions)
        {
            if (monitoringPerformanceResponseMetrics.LatencySourceOption.IsSet && monitoringPerformanceResponseMetrics.LatencySource == null)
                throw new ArgumentNullException(nameof(monitoringPerformanceResponseMetrics.LatencySource), "Property is required for class MonitoringPerformanceResponseMetrics.");

            if (monitoringPerformanceResponseMetrics.TotalRequestsOption.IsSet)
                writer.WriteNumber("totalRequests", monitoringPerformanceResponseMetrics.TotalRequestsOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.AvgResponseTimeOption.IsSet)
                writer.WriteNumber("avgResponseTime", monitoringPerformanceResponseMetrics.AvgResponseTimeOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.MinResponseTimeOption.IsSet)
                writer.WriteNumber("minResponseTime", monitoringPerformanceResponseMetrics.MinResponseTimeOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.MaxResponseTimeOption.IsSet)
                writer.WriteNumber("maxResponseTime", monitoringPerformanceResponseMetrics.MaxResponseTimeOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.ErrorCountOption.IsSet)
                writer.WriteNumber("errorCount", monitoringPerformanceResponseMetrics.ErrorCountOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.SuccessCountOption.IsSet)
                writer.WriteNumber("successCount", monitoringPerformanceResponseMetrics.SuccessCountOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.SuccessRateOption.IsSet)
                writer.WriteNumber("successRate", monitoringPerformanceResponseMetrics.SuccessRateOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.ErrorRateOption.IsSet)
                writer.WriteNumber("errorRate", monitoringPerformanceResponseMetrics.ErrorRateOption.Value!.Value);

            if (monitoringPerformanceResponseMetrics.LatencySourceOption.IsSet)
                writer.WriteString("latencySource", monitoringPerformanceResponseMetrics.LatencySource);
        }
    }
}
