/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.7
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mudbase.SDK.Client.FileParameter;
using OpenAPIDateConverter = Mudbase.SDK.Client.OpenAPIDateConverter;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// PresignedPostResponse
    /// </summary>
    [DataContract(Name = "PresignedPostResponse")]
    public partial class PresignedPostResponse : IValidatableObject
    {
        /// <summary>
        /// HTTP method the client must use against &#x60;url&#x60; (always PUT - R2 does not implement the S3 POST Object API)
        /// </summary>
        /// <value>HTTP method the client must use against &#x60;url&#x60; (always PUT - R2 does not implement the S3 POST Object API)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MethodEnum
        {
            /// <summary>
            /// Enum PUT for value: PUT
            /// </summary>
            [EnumMember(Value = "PUT")]
            PUT = 1
        }


        /// <summary>
        /// HTTP method the client must use against &#x60;url&#x60; (always PUT - R2 does not implement the S3 POST Object API)
        /// </summary>
        /// <value>HTTP method the client must use against &#x60;url&#x60; (always PUT - R2 does not implement the S3 POST Object API)</value>
        [DataMember(Name = "method", EmitDefaultValue = false)]
        public MethodEnum? Method { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PresignedPostResponse" /> class.
        /// </summary>
        /// <param name="key">Object key (S3) clients should upload to.</param>
        /// <param name="url">Presigned URL to PUT the file body to directly.</param>
        /// <param name="method">HTTP method the client must use against &#x60;url&#x60; (always PUT - R2 does not implement the S3 POST Object API).</param>
        /// <param name="headers">Headers the client must send with the PUT request (e.g. Content-Type) - mismatching these from what was signed causes a SignatureDoesNotMatch error.</param>
        /// <param name="expiresIn">Expiration of the presigned URL in seconds.</param>
        /// <param name="maxFileUploadBytes">Maximum upload size in bytes for this org plan. Not enforced by the presigned URL itself (PUT has no content-length-range equivalent) - checked server-side by /api/files/upload/confirm after the upload completes.</param>
        public PresignedPostResponse(string key = default, string url = default, MethodEnum? method = default, Object headers = default, int expiresIn = default, long maxFileUploadBytes = default)
        {
            this.Key = key;
            this.Url = url;
            this.Method = method;
            this.Headers = headers;
            this.ExpiresIn = expiresIn;
            this.MaxFileUploadBytes = maxFileUploadBytes;
        }

        /// <summary>
        /// Object key (S3) clients should upload to
        /// </summary>
        /// <value>Object key (S3) clients should upload to</value>
        [DataMember(Name = "key", EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// Presigned URL to PUT the file body to directly
        /// </summary>
        /// <value>Presigned URL to PUT the file body to directly</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Headers the client must send with the PUT request (e.g. Content-Type) - mismatching these from what was signed causes a SignatureDoesNotMatch error
        /// </summary>
        /// <value>Headers the client must send with the PUT request (e.g. Content-Type) - mismatching these from what was signed causes a SignatureDoesNotMatch error</value>
        [DataMember(Name = "headers", EmitDefaultValue = false)]
        public Object Headers { get; set; }

        /// <summary>
        /// Expiration of the presigned URL in seconds
        /// </summary>
        /// <value>Expiration of the presigned URL in seconds</value>
        [DataMember(Name = "expiresIn", EmitDefaultValue = false)]
        public int ExpiresIn { get; set; }

        /// <summary>
        /// Maximum upload size in bytes for this org plan. Not enforced by the presigned URL itself (PUT has no content-length-range equivalent) - checked server-side by /api/files/upload/confirm after the upload completes
        /// </summary>
        /// <value>Maximum upload size in bytes for this org plan. Not enforced by the presigned URL itself (PUT has no content-length-range equivalent) - checked server-side by /api/files/upload/confirm after the upload completes</value>
        [DataMember(Name = "maxFileUploadBytes", EmitDefaultValue = false)]
        public long MaxFileUploadBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PresignedPostResponse {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  MaxFileUploadBytes: ").Append(MaxFileUploadBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
