// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// SendMessageRequest
    /// </summary>
    public partial class SendMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendMessageRequest" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="content">Plaintext body; omit when sending e2ee (use e2ee.ciphertext for E2EE text)</param>
        /// <param name="e2ee">e2ee</param>
        /// <param name="replyTo">replyTo</param>
        /// <param name="mentions">mentions</param>
        [JsonConstructor]
        public SendMessageRequest(TypeEnum type, Option<string?> content = default, Option<SendMessageRequestE2ee?> e2ee = default, Option<string?> replyTo = default, Option<List<string>?> mentions = default)
        {
            Type = type;
            ContentOption = content;
            E2eeOption = e2ee;
            ReplyToOption = replyTo;
            MentionsOption = mentions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Text for value: text
            /// </summary>
            Text = 1,

            /// <summary>
            /// Enum Image for value: image
            /// </summary>
            Image = 2,

            /// <summary>
            /// Enum Video for value: video
            /// </summary>
            Video = 3,

            /// <summary>
            /// Enum Audio for value: audio
            /// </summary>
            Audio = 4,

            /// <summary>
            /// Enum File for value: file
            /// </summary>
            File = 5,

            /// <summary>
            /// Enum Location for value: location
            /// </summary>
            Location = 6,

            /// <summary>
            /// Enum Contact for value: contact
            /// </summary>
            Contact = 7
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("text"))
                return TypeEnum.Text;

            if (value.Equals("image"))
                return TypeEnum.Image;

            if (value.Equals("video"))
                return TypeEnum.Video;

            if (value.Equals("audio"))
                return TypeEnum.Audio;

            if (value.Equals("file"))
                return TypeEnum.File;

            if (value.Equals("location"))
                return TypeEnum.Location;

            if (value.Equals("contact"))
                return TypeEnum.Contact;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("text"))
                return TypeEnum.Text;

            if (value.Equals("image"))
                return TypeEnum.Image;

            if (value.Equals("video"))
                return TypeEnum.Video;

            if (value.Equals("audio"))
                return TypeEnum.Audio;

            if (value.Equals("file"))
                return TypeEnum.File;

            if (value.Equals("location"))
                return TypeEnum.Location;

            if (value.Equals("contact"))
                return TypeEnum.Contact;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Text)
                return "text";

            if (value == TypeEnum.Image)
                return "image";

            if (value == TypeEnum.Video)
                return "video";

            if (value == TypeEnum.Audio)
                return "audio";

            if (value == TypeEnum.File)
                return "file";

            if (value == TypeEnum.Location)
                return "location";

            if (value == TypeEnum.Contact)
                return "contact";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Used to track the state of Content
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContentOption { get; private set; }

        /// <summary>
        /// Plaintext body; omit when sending e2ee (use e2ee.ciphertext for E2EE text)
        /// </summary>
        /// <value>Plaintext body; omit when sending e2ee (use e2ee.ciphertext for E2EE text)</value>
        [JsonPropertyName("content")]
        public string? Content { get { return this.ContentOption; } set { this.ContentOption = new(value); } }

        /// <summary>
        /// Used to track the state of E2ee
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SendMessageRequestE2ee?> E2eeOption { get; private set; }

        /// <summary>
        /// Gets or Sets E2ee
        /// </summary>
        [JsonPropertyName("e2ee")]
        public SendMessageRequestE2ee? E2ee { get { return this.E2eeOption; } set { this.E2eeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReplyTo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReplyToOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReplyTo
        /// </summary>
        [JsonPropertyName("replyTo")]
        public string? ReplyTo { get { return this.ReplyToOption; } set { this.ReplyToOption = new(value); } }

        /// <summary>
        /// Used to track the state of Mentions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> MentionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Mentions
        /// </summary>
        [JsonPropertyName("mentions")]
        public List<string>? Mentions { get { return this.MentionsOption; } set { this.MentionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendMessageRequest {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  E2ee: ").Append(E2ee).Append("\n");
            sb.Append("  ReplyTo: ").Append(ReplyTo).Append("\n");
            sb.Append("  Mentions: ").Append(Mentions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendMessageRequest" />
    /// </summary>
    public class SendMessageRequestJsonConverter : JsonConverter<SendMessageRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SendMessageRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendMessageRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<SendMessageRequest.TypeEnum?> type = default;
            Option<string?> content = default;
            Option<SendMessageRequestE2ee?> e2ee = default;
            Option<string?> replyTo = default;
            Option<List<string>?> mentions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<SendMessageRequest.TypeEnum?>(SendMessageRequest.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "content":
                            content = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "e2ee":
                            e2ee = new Option<SendMessageRequestE2ee?>(JsonSerializer.Deserialize<SendMessageRequestE2ee>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "replyTo":
                            replyTo = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mentions":
                            mentions = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class SendMessageRequest.", nameof(type));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class SendMessageRequest.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class SendMessageRequest.");

            if (e2ee.IsSet && e2ee.Value == null)
                throw new ArgumentNullException(nameof(e2ee), "Property is not nullable for class SendMessageRequest.");

            if (replyTo.IsSet && replyTo.Value == null)
                throw new ArgumentNullException(nameof(replyTo), "Property is not nullable for class SendMessageRequest.");

            if (mentions.IsSet && mentions.Value == null)
                throw new ArgumentNullException(nameof(mentions), "Property is not nullable for class SendMessageRequest.");

            return new SendMessageRequest(type.Value!.Value!, content, e2ee, replyTo, mentions);
        }

        /// <summary>
        /// Serializes a <see cref="SendMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendMessageRequest sendMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendMessageRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendMessageRequest sendMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendMessageRequest.ContentOption.IsSet && sendMessageRequest.Content == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.Content), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.E2eeOption.IsSet && sendMessageRequest.E2ee == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.E2ee), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.ReplyToOption.IsSet && sendMessageRequest.ReplyTo == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.ReplyTo), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.MentionsOption.IsSet && sendMessageRequest.Mentions == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.Mentions), "Property is required for class SendMessageRequest.");

            var typeRawValue = SendMessageRequest.TypeEnumToJsonValue(sendMessageRequest.Type);
            writer.WriteString("type", typeRawValue);
            if (sendMessageRequest.ContentOption.IsSet)
                writer.WriteString("content", sendMessageRequest.Content);

            if (sendMessageRequest.E2eeOption.IsSet)
            {
                writer.WritePropertyName("e2ee");
                JsonSerializer.Serialize(writer, sendMessageRequest.E2ee, jsonSerializerOptions);
            }
            if (sendMessageRequest.ReplyToOption.IsSet)
                writer.WriteString("replyTo", sendMessageRequest.ReplyTo);

            if (sendMessageRequest.MentionsOption.IsSet)
            {
                writer.WritePropertyName("mentions");
                JsonSerializer.Serialize(writer, sendMessageRequest.Mentions, jsonSerializerOptions);
            }
        }
    }
}
