/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.5
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mudbase.SDK.Client.FileParameter;
using OpenAPIDateConverter = Mudbase.SDK.Client.OpenAPIDateConverter;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// SimulateAppPermissionsRequest
    /// </summary>
    [DataContract(Name = "simulateAppPermissions_request")]
    public partial class SimulateAppPermissionsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimulateAppPermissionsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SimulateAppPermissionsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SimulateAppPermissionsRequest" /> class.
        /// </summary>
        /// <param name="role">App role slug (same as &#x60;roleSlug&#x60; elsewhere) (required).</param>
        /// <param name="roleSlug">Alias for &#x60;role&#x60;.</param>
        /// <param name="operationId">OpenAPI operationId (e.g. &#x60;sendEmail&#x60;, &#x60;executeIntegration&#x60;). When set, path simulation is optional..</param>
        /// <param name="method">method.</param>
        /// <param name="pathname">Full path e.g. &#x60;/api/messaging/projects/{id}/messaging/email&#x60;.</param>
        /// <param name="path">Alias for &#x60;pathname&#x60;.</param>
        public SimulateAppPermissionsRequest(string role = default, string roleSlug = default, string operationId = default, string method = default, string pathname = default, string path = default)
        {
            // to ensure "role" is required (not null)
            if (role == null)
            {
                throw new ArgumentNullException("role is a required property for SimulateAppPermissionsRequest and cannot be null");
            }
            this.Role = role;
            this.RoleSlug = roleSlug;
            this.OperationId = operationId;
            this.Method = method;
            this.Pathname = pathname;
            this.Path = path;
        }

        /// <summary>
        /// App role slug (same as &#x60;roleSlug&#x60; elsewhere)
        /// </summary>
        /// <value>App role slug (same as &#x60;roleSlug&#x60; elsewhere)</value>
        /*
        <example>customer</example>
        */
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public string Role { get; set; }

        /// <summary>
        /// Alias for &#x60;role&#x60;
        /// </summary>
        /// <value>Alias for &#x60;role&#x60;</value>
        [DataMember(Name = "roleSlug", EmitDefaultValue = false)]
        public string RoleSlug { get; set; }

        /// <summary>
        /// OpenAPI operationId (e.g. &#x60;sendEmail&#x60;, &#x60;executeIntegration&#x60;). When set, path simulation is optional.
        /// </summary>
        /// <value>OpenAPI operationId (e.g. &#x60;sendEmail&#x60;, &#x60;executeIntegration&#x60;). When set, path simulation is optional.</value>
        /*
        <example>sendEmail</example>
        */
        [DataMember(Name = "operationId", EmitDefaultValue = false)]
        public string OperationId { get; set; }

        /// <summary>
        /// Gets or Sets Method
        /// </summary>
        /*
        <example>POST</example>
        */
        [DataMember(Name = "method", EmitDefaultValue = false)]
        public string Method { get; set; }

        /// <summary>
        /// Full path e.g. &#x60;/api/messaging/projects/{id}/messaging/email&#x60;
        /// </summary>
        /// <value>Full path e.g. &#x60;/api/messaging/projects/{id}/messaging/email&#x60;</value>
        /*
        <example>/api/messaging/projects/685ad30be129932fbb7a1047/messaging/email</example>
        */
        [DataMember(Name = "pathname", EmitDefaultValue = false)]
        public string Pathname { get; set; }

        /// <summary>
        /// Alias for &#x60;pathname&#x60;
        /// </summary>
        /// <value>Alias for &#x60;pathname&#x60;</value>
        [DataMember(Name = "path", EmitDefaultValue = false)]
        public string Path { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SimulateAppPermissionsRequest {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  RoleSlug: ").Append(RoleSlug).Append("\n");
            sb.Append("  OperationId: ").Append(OperationId).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Pathname: ").Append(Pathname).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
