// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.8
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// StorageConfirmUploadRequest
    /// </summary>
    public partial class StorageConfirmUploadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageConfirmUploadRequest" /> class.
        /// </summary>
        /// <param name="key">The S3 object key returned when the presigned POST was issued</param>
        /// <param name="projectId">projectId</param>
        /// <param name="originalName">originalName</param>
        /// <param name="contentType">contentType</param>
        /// <param name="size">size</param>
        /// <param name="bucket">bucket</param>
        /// <param name="isPublic">isPublic</param>
        [JsonConstructor]
        public StorageConfirmUploadRequest(string key, string projectId, Option<string?> originalName = default, Option<string?> contentType = default, Option<int?> size = default, Option<string?> bucket = default, Option<bool?> isPublic = default)
        {
            Key = key;
            ProjectId = projectId;
            OriginalNameOption = originalName;
            ContentTypeOption = contentType;
            SizeOption = size;
            BucketOption = bucket;
            IsPublicOption = isPublic;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The S3 object key returned when the presigned POST was issued
        /// </summary>
        /// <value>The S3 object key returned when the presigned POST was issued</value>
        [JsonPropertyName("key")]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("projectId")]
        public string ProjectId { get; set; }

        /// <summary>
        /// Used to track the state of OriginalName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OriginalNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets OriginalName
        /// </summary>
        [JsonPropertyName("originalName")]
        public string? OriginalName { get { return this.OriginalNameOption; } set { this.OriginalNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContentType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContentTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [JsonPropertyName("contentType")]
        public string? ContentType { get { return this.ContentTypeOption; } set { this.ContentTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Size
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [JsonPropertyName("size")]
        public int? Size { get { return this.SizeOption; } set { this.SizeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bucket
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BucketOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bucket
        /// </summary>
        [JsonPropertyName("bucket")]
        public string? Bucket { get { return this.BucketOption; } set { this.BucketOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsPublic
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsPublicOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsPublic
        /// </summary>
        [JsonPropertyName("isPublic")]
        public bool? IsPublic { get { return this.IsPublicOption; } set { this.IsPublicOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageConfirmUploadRequest {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  OriginalName: ").Append(OriginalName).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Bucket: ").Append(Bucket).Append("\n");
            sb.Append("  IsPublic: ").Append(IsPublic).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StorageConfirmUploadRequest" />
    /// </summary>
    public class StorageConfirmUploadRequestJsonConverter : JsonConverter<StorageConfirmUploadRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="StorageConfirmUploadRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StorageConfirmUploadRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> key = default;
            Option<string?> projectId = default;
            Option<string?> originalName = default;
            Option<string?> contentType = default;
            Option<int?> size = default;
            Option<string?> bucket = default;
            Option<bool?> isPublic = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "projectId":
                            projectId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "originalName":
                            originalName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "contentType":
                            contentType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "size":
                            size = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bucket":
                            bucket = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "isPublic":
                            isPublic = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!key.IsSet)
                throw new ArgumentException("Property is required for class StorageConfirmUploadRequest.", nameof(key));

            if (!projectId.IsSet)
                throw new ArgumentException("Property is required for class StorageConfirmUploadRequest.", nameof(projectId));

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class StorageConfirmUploadRequest.");

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class StorageConfirmUploadRequest.");

            if (originalName.IsSet && originalName.Value == null)
                throw new ArgumentNullException(nameof(originalName), "Property is not nullable for class StorageConfirmUploadRequest.");

            if (contentType.IsSet && contentType.Value == null)
                throw new ArgumentNullException(nameof(contentType), "Property is not nullable for class StorageConfirmUploadRequest.");

            if (size.IsSet && size.Value == null)
                throw new ArgumentNullException(nameof(size), "Property is not nullable for class StorageConfirmUploadRequest.");

            if (bucket.IsSet && bucket.Value == null)
                throw new ArgumentNullException(nameof(bucket), "Property is not nullable for class StorageConfirmUploadRequest.");

            if (isPublic.IsSet && isPublic.Value == null)
                throw new ArgumentNullException(nameof(isPublic), "Property is not nullable for class StorageConfirmUploadRequest.");

            return new StorageConfirmUploadRequest(key.Value!, projectId.Value!, originalName, contentType, size, bucket, isPublic);
        }

        /// <summary>
        /// Serializes a <see cref="StorageConfirmUploadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storageConfirmUploadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StorageConfirmUploadRequest storageConfirmUploadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, storageConfirmUploadRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StorageConfirmUploadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storageConfirmUploadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StorageConfirmUploadRequest storageConfirmUploadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (storageConfirmUploadRequest.Key == null)
                throw new ArgumentNullException(nameof(storageConfirmUploadRequest.Key), "Property is required for class StorageConfirmUploadRequest.");

            if (storageConfirmUploadRequest.ProjectId == null)
                throw new ArgumentNullException(nameof(storageConfirmUploadRequest.ProjectId), "Property is required for class StorageConfirmUploadRequest.");

            if (storageConfirmUploadRequest.OriginalNameOption.IsSet && storageConfirmUploadRequest.OriginalName == null)
                throw new ArgumentNullException(nameof(storageConfirmUploadRequest.OriginalName), "Property is required for class StorageConfirmUploadRequest.");

            if (storageConfirmUploadRequest.ContentTypeOption.IsSet && storageConfirmUploadRequest.ContentType == null)
                throw new ArgumentNullException(nameof(storageConfirmUploadRequest.ContentType), "Property is required for class StorageConfirmUploadRequest.");

            if (storageConfirmUploadRequest.BucketOption.IsSet && storageConfirmUploadRequest.Bucket == null)
                throw new ArgumentNullException(nameof(storageConfirmUploadRequest.Bucket), "Property is required for class StorageConfirmUploadRequest.");

            writer.WriteString("key", storageConfirmUploadRequest.Key);

            writer.WriteString("projectId", storageConfirmUploadRequest.ProjectId);

            if (storageConfirmUploadRequest.OriginalNameOption.IsSet)
                writer.WriteString("originalName", storageConfirmUploadRequest.OriginalName);

            if (storageConfirmUploadRequest.ContentTypeOption.IsSet)
                writer.WriteString("contentType", storageConfirmUploadRequest.ContentType);

            if (storageConfirmUploadRequest.SizeOption.IsSet)
                writer.WriteNumber("size", storageConfirmUploadRequest.SizeOption.Value!.Value);

            if (storageConfirmUploadRequest.BucketOption.IsSet)
                writer.WriteString("bucket", storageConfirmUploadRequest.Bucket);

            if (storageConfirmUploadRequest.IsPublicOption.IsSet)
                writer.WriteBoolean("isPublic", storageConfirmUploadRequest.IsPublicOption.Value!.Value);
        }
    }
}
