// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@dev.mudbase
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// SystemStatusResponseDataRequests
    /// </summary>
    public partial class SystemStatusResponseDataRequests : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemStatusResponseDataRequests" /> class.
        /// </summary>
        /// <param name="total">total</param>
        /// <param name="successful">successful</param>
        /// <param name="errors">errors</param>
        /// <param name="errorRate">errorRate</param>
        [JsonConstructor]
        public SystemStatusResponseDataRequests(Option<int?> total = default, Option<int?> successful = default, Option<int?> errors = default, Option<decimal?> errorRate = default)
        {
            TotalOption = total;
            SuccessfulOption = successful;
            ErrorsOption = errors;
            ErrorRateOption = errorRate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Total
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalOption { get; private set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public int? Total { get { return this.TotalOption; } set { this.TotalOption = new(value); } }

        /// <summary>
        /// Used to track the state of Successful
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SuccessfulOption { get; private set; }

        /// <summary>
        /// Gets or Sets Successful
        /// </summary>
        [JsonPropertyName("successful")]
        public int? Successful { get { return this.SuccessfulOption; } set { this.SuccessfulOption = new(value); } }

        /// <summary>
        /// Used to track the state of Errors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ErrorsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [JsonPropertyName("errors")]
        public int? Errors { get { return this.ErrorsOption; } set { this.ErrorsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ErrorRateOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorRate
        /// </summary>
        [JsonPropertyName("errorRate")]
        public decimal? ErrorRate { get { return this.ErrorRateOption; } set { this.ErrorRateOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemStatusResponseDataRequests {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  ErrorRate: ").Append(ErrorRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SystemStatusResponseDataRequests" />
    /// </summary>
    public class SystemStatusResponseDataRequestsJsonConverter : JsonConverter<SystemStatusResponseDataRequests>
    {
        /// <summary>
        /// Deserializes json to <see cref="SystemStatusResponseDataRequests" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SystemStatusResponseDataRequests Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> total = default;
            Option<int?> successful = default;
            Option<int?> errors = default;
            Option<decimal?> errorRate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "successful":
                            successful = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "errors":
                            errors = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "errorRate":
                            errorRate = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class SystemStatusResponseDataRequests.");

            if (successful.IsSet && successful.Value == null)
                throw new ArgumentNullException(nameof(successful), "Property is not nullable for class SystemStatusResponseDataRequests.");

            if (errors.IsSet && errors.Value == null)
                throw new ArgumentNullException(nameof(errors), "Property is not nullable for class SystemStatusResponseDataRequests.");

            if (errorRate.IsSet && errorRate.Value == null)
                throw new ArgumentNullException(nameof(errorRate), "Property is not nullable for class SystemStatusResponseDataRequests.");

            return new SystemStatusResponseDataRequests(total, successful, errors, errorRate);
        }

        /// <summary>
        /// Serializes a <see cref="SystemStatusResponseDataRequests" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemStatusResponseDataRequests"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SystemStatusResponseDataRequests systemStatusResponseDataRequests, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, systemStatusResponseDataRequests, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SystemStatusResponseDataRequests" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemStatusResponseDataRequests"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SystemStatusResponseDataRequests systemStatusResponseDataRequests, JsonSerializerOptions jsonSerializerOptions)
        {
            if (systemStatusResponseDataRequests.TotalOption.IsSet)
                writer.WriteNumber("total", systemStatusResponseDataRequests.TotalOption.Value!.Value);

            if (systemStatusResponseDataRequests.SuccessfulOption.IsSet)
                writer.WriteNumber("successful", systemStatusResponseDataRequests.SuccessfulOption.Value!.Value);

            if (systemStatusResponseDataRequests.ErrorsOption.IsSet)
                writer.WriteNumber("errors", systemStatusResponseDataRequests.ErrorsOption.Value!.Value);

            if (systemStatusResponseDataRequests.ErrorRateOption.IsSet)
                writer.WriteNumber("errorRate", systemStatusResponseDataRequests.ErrorRateOption.Value!.Value);
        }
    }
}
