// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// UpdateWalletFeeConfig200ResponseData
    /// </summary>
    public partial class UpdateWalletFeeConfig200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateWalletFeeConfig200ResponseData" /> class.
        /// </summary>
        /// <param name="enabled">enabled</param>
        /// <param name="feePercentage">feePercentage</param>
        [JsonConstructor]
        public UpdateWalletFeeConfig200ResponseData(Option<bool?> enabled = default, Option<decimal?> feePercentage = default)
        {
            EnabledOption = enabled;
            FeePercentageOption = feePercentage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool? Enabled { get { return this.EnabledOption; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of FeePercentage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> FeePercentageOption { get; private set; }

        /// <summary>
        /// Gets or Sets FeePercentage
        /// </summary>
        [JsonPropertyName("feePercentage")]
        public decimal? FeePercentage { get { return this.FeePercentageOption; } set { this.FeePercentageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateWalletFeeConfig200ResponseData {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  FeePercentage: ").Append(FeePercentage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateWalletFeeConfig200ResponseData" />
    /// </summary>
    public class UpdateWalletFeeConfig200ResponseDataJsonConverter : JsonConverter<UpdateWalletFeeConfig200ResponseData>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateWalletFeeConfig200ResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateWalletFeeConfig200ResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> enabled = default;
            Option<decimal?> feePercentage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "feePercentage":
                            feePercentage = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class UpdateWalletFeeConfig200ResponseData.");

            if (feePercentage.IsSet && feePercentage.Value == null)
                throw new ArgumentNullException(nameof(feePercentage), "Property is not nullable for class UpdateWalletFeeConfig200ResponseData.");

            return new UpdateWalletFeeConfig200ResponseData(enabled, feePercentage);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateWalletFeeConfig200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateWalletFeeConfig200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateWalletFeeConfig200ResponseData updateWalletFeeConfig200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateWalletFeeConfig200ResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateWalletFeeConfig200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateWalletFeeConfig200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateWalletFeeConfig200ResponseData updateWalletFeeConfig200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateWalletFeeConfig200ResponseData.EnabledOption.IsSet)
                writer.WriteBoolean("enabled", updateWalletFeeConfig200ResponseData.EnabledOption.Value!.Value);

            if (updateWalletFeeConfig200ResponseData.FeePercentageOption.IsSet)
                writer.WriteNumber("feePercentage", updateWalletFeeConfig200ResponseData.FeePercentageOption.Value!.Value);
        }
    }
}
