// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// UsageTrendsResponseTrendsInner
    /// </summary>
    public partial class UsageTrendsResponseTrendsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageTrendsResponseTrendsInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="apiCalls">apiCalls</param>
        /// <param name="storage">storage</param>
        /// <param name="bandwidth">bandwidth</param>
        /// <param name="dbReads">dbReads</param>
        /// <param name="dbWrites">dbWrites</param>
        [JsonConstructor]
        public UsageTrendsResponseTrendsInner(Option<UsageTrendsResponseTrendsInnerId?> id = default, Option<int?> apiCalls = default, Option<int?> storage = default, Option<int?> bandwidth = default, Option<int?> dbReads = default, Option<int?> dbWrites = default)
        {
            IdOption = id;
            ApiCallsOption = apiCalls;
            StorageOption = storage;
            BandwidthOption = bandwidth;
            DbReadsOption = dbReads;
            DbWritesOption = dbWrites;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<UsageTrendsResponseTrendsInnerId?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("_id")]
        public UsageTrendsResponseTrendsInnerId? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApiCalls
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ApiCallsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiCalls
        /// </summary>
        [JsonPropertyName("apiCalls")]
        public int? ApiCalls { get { return this.ApiCallsOption; } set { this.ApiCallsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Storage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> StorageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Storage
        /// </summary>
        [JsonPropertyName("storage")]
        public int? Storage { get { return this.StorageOption; } set { this.StorageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bandwidth
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BandwidthOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bandwidth
        /// </summary>
        [JsonPropertyName("bandwidth")]
        public int? Bandwidth { get { return this.BandwidthOption; } set { this.BandwidthOption = new(value); } }

        /// <summary>
        /// Used to track the state of DbReads
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DbReadsOption { get; private set; }

        /// <summary>
        /// Gets or Sets DbReads
        /// </summary>
        [JsonPropertyName("dbReads")]
        public int? DbReads { get { return this.DbReadsOption; } set { this.DbReadsOption = new(value); } }

        /// <summary>
        /// Used to track the state of DbWrites
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DbWritesOption { get; private set; }

        /// <summary>
        /// Gets or Sets DbWrites
        /// </summary>
        [JsonPropertyName("dbWrites")]
        public int? DbWrites { get { return this.DbWritesOption; } set { this.DbWritesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UsageTrendsResponseTrendsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ApiCalls: ").Append(ApiCalls).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  Bandwidth: ").Append(Bandwidth).Append("\n");
            sb.Append("  DbReads: ").Append(DbReads).Append("\n");
            sb.Append("  DbWrites: ").Append(DbWrites).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UsageTrendsResponseTrendsInner" />
    /// </summary>
    public class UsageTrendsResponseTrendsInnerJsonConverter : JsonConverter<UsageTrendsResponseTrendsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="UsageTrendsResponseTrendsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UsageTrendsResponseTrendsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<UsageTrendsResponseTrendsInnerId?> id = default;
            Option<int?> apiCalls = default;
            Option<int?> storage = default;
            Option<int?> bandwidth = default;
            Option<int?> dbReads = default;
            Option<int?> dbWrites = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "_id":
                            id = new Option<UsageTrendsResponseTrendsInnerId?>(JsonSerializer.Deserialize<UsageTrendsResponseTrendsInnerId>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "apiCalls":
                            apiCalls = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "storage":
                            storage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bandwidth":
                            bandwidth = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "dbReads":
                            dbReads = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "dbWrites":
                            dbWrites = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class UsageTrendsResponseTrendsInner.");

            if (apiCalls.IsSet && apiCalls.Value == null)
                throw new ArgumentNullException(nameof(apiCalls), "Property is not nullable for class UsageTrendsResponseTrendsInner.");

            if (storage.IsSet && storage.Value == null)
                throw new ArgumentNullException(nameof(storage), "Property is not nullable for class UsageTrendsResponseTrendsInner.");

            if (bandwidth.IsSet && bandwidth.Value == null)
                throw new ArgumentNullException(nameof(bandwidth), "Property is not nullable for class UsageTrendsResponseTrendsInner.");

            if (dbReads.IsSet && dbReads.Value == null)
                throw new ArgumentNullException(nameof(dbReads), "Property is not nullable for class UsageTrendsResponseTrendsInner.");

            if (dbWrites.IsSet && dbWrites.Value == null)
                throw new ArgumentNullException(nameof(dbWrites), "Property is not nullable for class UsageTrendsResponseTrendsInner.");

            return new UsageTrendsResponseTrendsInner(id, apiCalls, storage, bandwidth, dbReads, dbWrites);
        }

        /// <summary>
        /// Serializes a <see cref="UsageTrendsResponseTrendsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="usageTrendsResponseTrendsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UsageTrendsResponseTrendsInner usageTrendsResponseTrendsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, usageTrendsResponseTrendsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UsageTrendsResponseTrendsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="usageTrendsResponseTrendsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UsageTrendsResponseTrendsInner usageTrendsResponseTrendsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (usageTrendsResponseTrendsInner.IdOption.IsSet && usageTrendsResponseTrendsInner.Id == null)
                throw new ArgumentNullException(nameof(usageTrendsResponseTrendsInner.Id), "Property is required for class UsageTrendsResponseTrendsInner.");

            if (usageTrendsResponseTrendsInner.IdOption.IsSet)
            {
                writer.WritePropertyName("_id");
                JsonSerializer.Serialize(writer, usageTrendsResponseTrendsInner.Id, jsonSerializerOptions);
            }
            if (usageTrendsResponseTrendsInner.ApiCallsOption.IsSet)
                writer.WriteNumber("apiCalls", usageTrendsResponseTrendsInner.ApiCallsOption.Value!.Value);

            if (usageTrendsResponseTrendsInner.StorageOption.IsSet)
                writer.WriteNumber("storage", usageTrendsResponseTrendsInner.StorageOption.Value!.Value);

            if (usageTrendsResponseTrendsInner.BandwidthOption.IsSet)
                writer.WriteNumber("bandwidth", usageTrendsResponseTrendsInner.BandwidthOption.Value!.Value);

            if (usageTrendsResponseTrendsInner.DbReadsOption.IsSet)
                writer.WriteNumber("dbReads", usageTrendsResponseTrendsInner.DbReadsOption.Value!.Value);

            if (usageTrendsResponseTrendsInner.DbWritesOption.IsSet)
                writer.WriteNumber("dbWrites", usageTrendsResponseTrendsInner.DbWritesOption.Value!.Value);
        }
    }
}
