/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.7
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mudbase.SDK.Client.FileParameter;
using OpenAPIDateConverter = Mudbase.SDK.Client.OpenAPIDateConverter;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// WalletWebhook
    /// </summary>
    [DataContract(Name = "WalletWebhook")]
    public partial class WalletWebhook : IValidatableObject
    {
        /// <summary>
        /// Defines Events
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventsEnum
        {
            /// <summary>
            /// Enum WalletBalanceUpdated for value: wallet.balance.updated
            /// </summary>
            [EnumMember(Value = "wallet.balance.updated")]
            WalletBalanceUpdated = 1,

            /// <summary>
            /// Enum WalletTransactionConfirmed for value: wallet.transaction.confirmed
            /// </summary>
            [EnumMember(Value = "wallet.transaction.confirmed")]
            WalletTransactionConfirmed = 2,

            /// <summary>
            /// Enum WalletTransactionFailed for value: wallet.transaction.failed
            /// </summary>
            [EnumMember(Value = "wallet.transaction.failed")]
            WalletTransactionFailed = 3
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletWebhook" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="url">url.</param>
        /// <param name="events">events.</param>
        /// <param name="filters">filters.</param>
        /// <param name="isActive">isActive.</param>
        /// <param name="stats">stats.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        public WalletWebhook(string id = default, string url = default, List<EventsEnum> events = default, WalletWebhookFilters filters = default, bool isActive = default, WalletWebhookStats stats = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            this.Id = id;
            this.Url = url;
            this.Events = events;
            this.Filters = filters;
            this.IsActive = isActive;
            this.Stats = stats;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>65a1b2c3d4e5f6789012345c</example>
        */
        [DataMember(Name = "_id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        /*
        <example>https://your-app.com/webhooks/wallet</example>
        */
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        /*
        <example>[&quot;wallet.balance.updated&quot;,&quot;wallet.transaction.confirmed&quot;]</example>
        */
        [DataMember(Name = "events", EmitDefaultValue = false)]
        public List<WalletWebhook.EventsEnum> Events { get; set; }

        /// <summary>
        /// Gets or Sets Filters
        /// </summary>
        [DataMember(Name = "filters", EmitDefaultValue = false)]
        public WalletWebhookFilters Filters { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isActive", EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets Stats
        /// </summary>
        [DataMember(Name = "stats", EmitDefaultValue = false)]
        public WalletWebhookStats Stats { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>2026-01-22T10:00Z</example>
        */
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /*
        <example>2026-01-22T10:00Z</example>
        */
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletWebhook {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
