// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@dev.mudbase
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// Example webhook payload for wallet.transaction.confirmed (reusable example payload).
    /// </summary>
    public partial class WalletTransactionWebhookPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionWebhookPayload" /> class.
        /// </summary>
        /// <param name="event">event</param>
        /// <param name="data">Payload data (addressId, address, chain, txHash, transaction, etc.)</param>
        /// <param name="timestamp">timestamp</param>
        [JsonConstructor]
        public WalletTransactionWebhookPayload(Option<string?> @event = default, Option<Object?> data = default, Option<DateTime?> timestamp = default)
        {
            EventOption = @event;
            DataOption = data;
            TimestampOption = timestamp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Event
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EventOption { get; private set; }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        /* <example>wallet.transaction.confirmed</example> */
        [JsonPropertyName("event")]
        public string? Event { get { return this.EventOption; } set { this.EventOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> DataOption { get; private set; }

        /// <summary>
        /// Payload data (addressId, address, chain, txHash, transaction, etc.)
        /// </summary>
        /// <value>Payload data (addressId, address, chain, txHash, transaction, etc.)</value>
        [JsonPropertyName("data")]
        public Object? Data { get { return this.DataOption; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        /* <example>2026-02-01T21:05:16.462Z</example> */
        [JsonPropertyName("timestamp")]
        public DateTime? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletTransactionWebhookPayload {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletTransactionWebhookPayload" />
    /// </summary>
    public class WalletTransactionWebhookPayloadJsonConverter : JsonConverter<WalletTransactionWebhookPayload>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="WalletTransactionWebhookPayload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WalletTransactionWebhookPayload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> varEvent = default;
            Option<Object?> data = default;
            Option<DateTime?> timestamp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "event":
                            varEvent = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "data":
                            data = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (varEvent.IsSet && varEvent.Value == null)
                throw new ArgumentNullException(nameof(varEvent), "Property is not nullable for class WalletTransactionWebhookPayload.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class WalletTransactionWebhookPayload.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class WalletTransactionWebhookPayload.");

            return new WalletTransactionWebhookPayload(varEvent, data, timestamp);
        }

        /// <summary>
        /// Serializes a <see cref="WalletTransactionWebhookPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransactionWebhookPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WalletTransactionWebhookPayload walletTransactionWebhookPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, walletTransactionWebhookPayload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WalletTransactionWebhookPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransactionWebhookPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WalletTransactionWebhookPayload walletTransactionWebhookPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (walletTransactionWebhookPayload.EventOption.IsSet && walletTransactionWebhookPayload.Event == null)
                throw new ArgumentNullException(nameof(walletTransactionWebhookPayload.Event), "Property is required for class WalletTransactionWebhookPayload.");

            if (walletTransactionWebhookPayload.DataOption.IsSet && walletTransactionWebhookPayload.Data == null)
                throw new ArgumentNullException(nameof(walletTransactionWebhookPayload.Data), "Property is required for class WalletTransactionWebhookPayload.");

            if (walletTransactionWebhookPayload.EventOption.IsSet)
                writer.WriteString("event", walletTransactionWebhookPayload.Event);

            if (walletTransactionWebhookPayload.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, walletTransactionWebhookPayload.Data, jsonSerializerOptions);
            }
            if (walletTransactionWebhookPayload.TimestampOption.IsSet)
                writer.WriteString("timestamp", walletTransactionWebhookPayload.TimestampOption.Value!.Value.ToString(TimestampFormat));
        }
    }
}
