// <auto-generated>
/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Mudbase.SDK.Client;

namespace Mudbase.SDK.Model
{
    /// <summary>
    /// WalletTransactionTokenTransfersInner
    /// </summary>
    public partial class WalletTransactionTokenTransfersInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionTokenTransfersInner" /> class.
        /// </summary>
        /// <param name="tokenAddress">tokenAddress</param>
        /// <param name="from">from</param>
        /// <param name="to">to</param>
        /// <param name="value">Raw token units (string to preserve precision)</param>
        /// <param name="formattedAmount">Human-readable token amount (units)</param>
        /// <param name="tokenSymbol">tokenSymbol</param>
        /// <param name="tokenDecimals">tokenDecimals</param>
        /// <param name="isIncoming">isIncoming</param>
        [JsonConstructor]
        public WalletTransactionTokenTransfersInner(Option<string?> tokenAddress = default, Option<string?> from = default, Option<string?> to = default, Option<string?> value = default, Option<string?> formattedAmount = default, Option<string?> tokenSymbol = default, Option<int?> tokenDecimals = default, Option<bool?> isIncoming = default)
        {
            TokenAddressOption = tokenAddress;
            FromOption = from;
            ToOption = to;
            ValueOption = value;
            FormattedAmountOption = formattedAmount;
            TokenSymbolOption = tokenSymbol;
            TokenDecimalsOption = tokenDecimals;
            IsIncomingOption = isIncoming;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TokenAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets TokenAddress
        /// </summary>
        /* <example>0x48065fbbe25f71c9282ddf5e1cd6d6a887483d5e</example> */
        [JsonPropertyName("tokenAddress")]
        public string? TokenAddress { get { return this.TokenAddressOption; } set { this.TokenAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of From
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FromOption { get; private set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        /* <example>0x1194d844f5c5a9adc488835e1f506dafbb579341</example> */
        [JsonPropertyName("from")]
        public string? From { get { return this.FromOption; } set { this.FromOption = new(value); } }

        /// <summary>
        /// Used to track the state of To
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ToOption { get; private set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        /* <example>0x000000000000000000000000000000000ce106a5</example> */
        [JsonPropertyName("to")]
        public string? To { get { return this.ToOption; } set { this.ToOption = new(value); } }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ValueOption { get; private set; }

        /// <summary>
        /// Raw token units (string to preserve precision)
        /// </summary>
        /// <value>Raw token units (string to preserve precision)</value>
        /* <example>80</example> */
        [JsonPropertyName("value")]
        public string? Value { get { return this.ValueOption; } set { this.ValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of FormattedAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FormattedAmountOption { get; private set; }

        /// <summary>
        /// Human-readable token amount (units)
        /// </summary>
        /// <value>Human-readable token amount (units)</value>
        /* <example>0.000076</example> */
        [JsonPropertyName("formattedAmount")]
        public string? FormattedAmount { get { return this.FormattedAmountOption; } set { this.FormattedAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TokenSymbol
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenSymbolOption { get; private set; }

        /// <summary>
        /// Gets or Sets TokenSymbol
        /// </summary>
        /* <example>USDT</example> */
        [JsonPropertyName("tokenSymbol")]
        public string? TokenSymbol { get { return this.TokenSymbolOption; } set { this.TokenSymbolOption = new(value); } }

        /// <summary>
        /// Used to track the state of TokenDecimals
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TokenDecimalsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TokenDecimals
        /// </summary>
        /* <example>6</example> */
        [JsonPropertyName("tokenDecimals")]
        public int? TokenDecimals { get { return this.TokenDecimalsOption; } set { this.TokenDecimalsOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsIncoming
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsIncomingOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsIncoming
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("isIncoming")]
        public bool? IsIncoming { get { return this.IsIncomingOption; } set { this.IsIncomingOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletTransactionTokenTransfersInner {\n");
            sb.Append("  TokenAddress: ").Append(TokenAddress).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  FormattedAmount: ").Append(FormattedAmount).Append("\n");
            sb.Append("  TokenSymbol: ").Append(TokenSymbol).Append("\n");
            sb.Append("  TokenDecimals: ").Append(TokenDecimals).Append("\n");
            sb.Append("  IsIncoming: ").Append(IsIncoming).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletTransactionTokenTransfersInner" />
    /// </summary>
    public class WalletTransactionTokenTransfersInnerJsonConverter : JsonConverter<WalletTransactionTokenTransfersInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="WalletTransactionTokenTransfersInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WalletTransactionTokenTransfersInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> tokenAddress = default;
            Option<string?> from = default;
            Option<string?> to = default;
            Option<string?> value = default;
            Option<string?> formattedAmount = default;
            Option<string?> tokenSymbol = default;
            Option<int?> tokenDecimals = default;
            Option<bool?> isIncoming = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "tokenAddress":
                            tokenAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "from":
                            from = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "to":
                            to = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "formattedAmount":
                            formattedAmount = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tokenSymbol":
                            tokenSymbol = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tokenDecimals":
                            tokenDecimals = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "isIncoming":
                            isIncoming = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (tokenAddress.IsSet && tokenAddress.Value == null)
                throw new ArgumentNullException(nameof(tokenAddress), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            if (formattedAmount.IsSet && formattedAmount.Value == null)
                throw new ArgumentNullException(nameof(formattedAmount), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            if (tokenSymbol.IsSet && tokenSymbol.Value == null)
                throw new ArgumentNullException(nameof(tokenSymbol), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            if (tokenDecimals.IsSet && tokenDecimals.Value == null)
                throw new ArgumentNullException(nameof(tokenDecimals), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            if (isIncoming.IsSet && isIncoming.Value == null)
                throw new ArgumentNullException(nameof(isIncoming), "Property is not nullable for class WalletTransactionTokenTransfersInner.");

            return new WalletTransactionTokenTransfersInner(tokenAddress, from, to, value, formattedAmount, tokenSymbol, tokenDecimals, isIncoming);
        }

        /// <summary>
        /// Serializes a <see cref="WalletTransactionTokenTransfersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransactionTokenTransfersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WalletTransactionTokenTransfersInner walletTransactionTokenTransfersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, walletTransactionTokenTransfersInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WalletTransactionTokenTransfersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransactionTokenTransfersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WalletTransactionTokenTransfersInner walletTransactionTokenTransfersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (walletTransactionTokenTransfersInner.TokenAddressOption.IsSet && walletTransactionTokenTransfersInner.TokenAddress == null)
                throw new ArgumentNullException(nameof(walletTransactionTokenTransfersInner.TokenAddress), "Property is required for class WalletTransactionTokenTransfersInner.");

            if (walletTransactionTokenTransfersInner.FromOption.IsSet && walletTransactionTokenTransfersInner.From == null)
                throw new ArgumentNullException(nameof(walletTransactionTokenTransfersInner.From), "Property is required for class WalletTransactionTokenTransfersInner.");

            if (walletTransactionTokenTransfersInner.ToOption.IsSet && walletTransactionTokenTransfersInner.To == null)
                throw new ArgumentNullException(nameof(walletTransactionTokenTransfersInner.To), "Property is required for class WalletTransactionTokenTransfersInner.");

            if (walletTransactionTokenTransfersInner.ValueOption.IsSet && walletTransactionTokenTransfersInner.Value == null)
                throw new ArgumentNullException(nameof(walletTransactionTokenTransfersInner.Value), "Property is required for class WalletTransactionTokenTransfersInner.");

            if (walletTransactionTokenTransfersInner.FormattedAmountOption.IsSet && walletTransactionTokenTransfersInner.FormattedAmount == null)
                throw new ArgumentNullException(nameof(walletTransactionTokenTransfersInner.FormattedAmount), "Property is required for class WalletTransactionTokenTransfersInner.");

            if (walletTransactionTokenTransfersInner.TokenSymbolOption.IsSet && walletTransactionTokenTransfersInner.TokenSymbol == null)
                throw new ArgumentNullException(nameof(walletTransactionTokenTransfersInner.TokenSymbol), "Property is required for class WalletTransactionTokenTransfersInner.");

            if (walletTransactionTokenTransfersInner.TokenAddressOption.IsSet)
                writer.WriteString("tokenAddress", walletTransactionTokenTransfersInner.TokenAddress);

            if (walletTransactionTokenTransfersInner.FromOption.IsSet)
                writer.WriteString("from", walletTransactionTokenTransfersInner.From);

            if (walletTransactionTokenTransfersInner.ToOption.IsSet)
                writer.WriteString("to", walletTransactionTokenTransfersInner.To);

            if (walletTransactionTokenTransfersInner.ValueOption.IsSet)
                writer.WriteString("value", walletTransactionTokenTransfersInner.Value);

            if (walletTransactionTokenTransfersInner.FormattedAmountOption.IsSet)
                writer.WriteString("formattedAmount", walletTransactionTokenTransfersInner.FormattedAmount);

            if (walletTransactionTokenTransfersInner.TokenSymbolOption.IsSet)
                writer.WriteString("tokenSymbol", walletTransactionTokenTransfersInner.TokenSymbol);

            if (walletTransactionTokenTransfersInner.TokenDecimalsOption.IsSet)
                writer.WriteNumber("tokenDecimals", walletTransactionTokenTransfersInner.TokenDecimalsOption.Value!.Value);

            if (walletTransactionTokenTransfersInner.IsIncomingOption.IsSet)
                writer.WriteBoolean("isIncoming", walletTransactionTokenTransfersInner.IsIncomingOption.Value!.Value);
        }
    }
}
