/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Mudbase.SDK.Api;
using Mudbase.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Mudbase.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing AddOnsApi
    /// </summary>
    public sealed class AddOnsApiTests : ApiTestsBase
    {
        private readonly IAddOnsApi _instance;

        public AddOnsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAddOnsApi>();
        }

        /// <summary>
        /// Test ApiAddonsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiAddonsGetAsyncTest()
        {
            var response = await _instance.ApiAddonsGetAsync();
            var model = response.Ok();
            Assert.IsType<ApiAddonsGet200Response>(model);
        }

        /// <summary>
        /// Test ApiProjectsProjectIdAddonsAddonInvokePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiProjectsProjectIdAddonsAddonInvokePostAsyncTest()
        {
            string projectId = default!;
            string addon = default!;
            Client.Option<Object> body = default!;
            var response = await _instance.ApiProjectsProjectIdAddonsAddonInvokePostAsync(projectId, addon, body);
            var model = response.Ok();
            Assert.IsType<ApiProjectsProjectIdAddonsAddonInvokePost200Response>(model);
        }

        /// <summary>
        /// Test ApiProjectsProjectIdAddonsJobsIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiProjectsProjectIdAddonsJobsIdGetAsyncTest()
        {
            string projectId = default!;
            string id = default!;
            var response = await _instance.ApiProjectsProjectIdAddonsJobsIdGetAsync(projectId, id);
            var model = response.Ok();
            Assert.IsType<ApiProjectsProjectIdAddonsAddonInvokePost200Response>(model);
        }
    }
}
