/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.5
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Mudbase.SDK.Client;
using Mudbase.SDK.Api;
// uncomment below to import models
//using Mudbase.SDK.Model;

namespace Mudbase.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing APIKeysApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class APIKeysApiTests : IDisposable
    {
        private APIKeysApi instance;

        public APIKeysApiTests()
        {
            instance = new APIKeysApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of APIKeysApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' APIKeysApi
            //Assert.IsType<APIKeysApi>(instance);
        }

        /// <summary>
        /// Test CreateApiKey
        /// </summary>
        [Fact]
        public void CreateApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateApiKeyRequest createApiKeyRequest = null;
            //var response = instance.CreateApiKey(createApiKeyRequest);
            //Assert.IsType<CreateApiKey201Response>(response);
        }

        /// <summary>
        /// Test DeleteApiKey
        /// </summary>
        [Fact]
        public void DeleteApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeleteApiKey(id);
            //Assert.IsType<MessageResponse>(response);
        }

        /// <summary>
        /// Test GetApiKeyUsage
        /// </summary>
        [Fact]
        public void GetApiKeyUsageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetApiKeyUsage(id);
            //Assert.IsType<ApiKeyUsageResponse>(response);
        }

        /// <summary>
        /// Test ListApiKeys
        /// </summary>
        [Fact]
        public void ListApiKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListApiKeys();
            //Assert.IsType<ListApiKeys200Response>(response);
        }

        /// <summary>
        /// Test RegenerateApiKey
        /// </summary>
        [Fact]
        public void RegenerateApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.RegenerateApiKey(id);
            //Assert.IsType<RegenerateApiKey200Response>(response);
        }

        /// <summary>
        /// Test UpdateApiKey
        /// </summary>
        [Fact]
        public void UpdateApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateApiKeyRequest updateApiKeyRequest = null;
            //var response = instance.UpdateApiKey(id, updateApiKeyRequest);
            //Assert.IsType<UpdateApiKey200Response>(response);
        }
    }
}
