/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Mudbase.SDK.Api;
using Mudbase.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Mudbase.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing IntegrationsApi
    /// </summary>
    public sealed class IntegrationsApiTests : ApiTestsBase
    {
        private readonly IIntegrationsApi _instance;

        public IntegrationsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IIntegrationsApi>();
        }

        /// <summary>
        /// Test CreateFromTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateFromTemplateAsyncTest()
        {
            string projectId = default!;
            CreateFromTemplateRequest createFromTemplateRequest = default!;
            var response = await _instance.CreateFromTemplateAsync(projectId, createFromTemplateRequest);
            var model = response.Created();
            Assert.IsType<CreateIntegration201Response>(model);
        }

        /// <summary>
        /// Test CreateIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateIntegrationAsyncTest()
        {
            string projectId = default!;
            CreateIntegrationRequest createIntegrationRequest = default!;
            var response = await _instance.CreateIntegrationAsync(projectId, createIntegrationRequest);
            var model = response.Created();
            Assert.IsType<CreateIntegration201Response>(model);
        }

        /// <summary>
        /// Test DeleteIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteIntegrationAsyncTest()
        {
            string projectId = default!;
            string integrationId = default!;
            var response = await _instance.DeleteIntegrationAsync(projectId, integrationId);
            var model = response.Ok();
            Assert.IsType<MessageResponse>(model);
        }

        /// <summary>
        /// Test ExecuteIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ExecuteIntegrationAsyncTest()
        {
            string projectId = default!;
            string integrationId = default!;
            ExecuteIntegrationRequest executeIntegrationRequest = default!;
            var response = await _instance.ExecuteIntegrationAsync(projectId, integrationId, executeIntegrationRequest);
            var model = response.Ok();
            Assert.IsType<TestWalletWebhook200Response>(model);
        }

        /// <summary>
        /// Test ExportIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ExportIntegrationAsyncTest()
        {
            string projectId = default!;
            string integrationId = default!;
            var response = await _instance.ExportIntegrationAsync(projectId, integrationId);
            var model = response.Ok();
            Assert.IsType<CreateIntegration201Response>(model);
        }

        /// <summary>
        /// Test GetIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetIntegrationAsyncTest()
        {
            string projectId = default!;
            string integrationId = default!;
            var response = await _instance.GetIntegrationAsync(projectId, integrationId);
            var model = response.Ok();
            Assert.IsType<GetIntegration200Response>(model);
        }

        /// <summary>
        /// Test GetIntegrations
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetIntegrationsAsyncTest()
        {
            string projectId = default!;
            var response = await _instance.GetIntegrationsAsync(projectId);
            var model = response.Ok();
            Assert.IsType<GetIntegrations200Response>(model);
        }

        /// <summary>
        /// Test GetTemplates
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetTemplatesAsyncTest()
        {
            var response = await _instance.GetTemplatesAsync();
            var model = response.Ok();
            Assert.IsType<GetTemplates200Response>(model);
        }

        /// <summary>
        /// Test GetUsageStats
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetUsageStatsAsyncTest()
        {
            string projectId = default!;
            string integrationId = default!;
            Client.Option<string> period = default!;
            var response = await _instance.GetUsageStatsAsync(projectId, integrationId, period);
            var model = response.Ok();
            Assert.IsType<GetUsageStats200Response>(model);
        }

        /// <summary>
        /// Test ImportIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ImportIntegrationAsyncTest()
        {
            string projectId = default!;
            ImportIntegrationRequest importIntegrationRequest = default!;
            var response = await _instance.ImportIntegrationAsync(projectId, importIntegrationRequest);
            var model = response.Created();
            Assert.IsType<CreateIntegration201Response>(model);
        }

        /// <summary>
        /// Test TestIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TestIntegrationAsyncTest()
        {
            string projectId = default!;
            string integrationId = default!;
            TestIntegrationRequest testIntegrationRequest = default!;
            var response = await _instance.TestIntegrationAsync(projectId, integrationId, testIntegrationRequest);
            var model = response.Ok();
            Assert.IsType<TestWalletWebhook200Response>(model);
        }

        /// <summary>
        /// Test UpdateIntegration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateIntegrationAsyncTest()
        {
            string projectId = default!;
            string integrationId = default!;
            UpdateIntegrationRequest updateIntegrationRequest = default!;
            var response = await _instance.UpdateIntegrationAsync(projectId, integrationId, updateIntegrationRequest);
            var model = response.Ok();
            Assert.IsType<CreateIntegration201Response>(model);
        }
    }
}
