/*
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@dev.mudbase
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Mudbase.SDK.Api;
using Mudbase.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Mudbase.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing WebhooksApi
    /// </summary>
    public sealed class WebhooksApiTests : ApiTestsBase
    {
        private readonly IWebhooksApi _instance;

        public WebhooksApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IWebhooksApi>();
        }

        /// <summary>
        /// Test WebhooksGetStats
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task WebhooksGetStatsAsyncTest()
        {
            Client.Option<string> projectId = default!;
            Client.Option<int> days = default!;
            var response = await _instance.WebhooksGetStatsAsync(projectId, days);
            var model = response.Ok();
            Assert.IsType<WebhookStatsResponse>(model);
        }
    }
}
